# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_tracer_laws.ui'
#
# Created: Wed Dec 20 18:40:38 2017
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_TracerLaws(object):
    def setupUi(self, TracerLaws):
        TracerLaws.setObjectName(_fromUtf8("TracerLaws"))
        TracerLaws.resize(730, 604)
        self.gridLayout_2 = QtGui.QGridLayout(TracerLaws)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.Law_pages = QtGui.QStackedWidget(TracerLaws)
        self.Law_pages.setEnabled(True)
        self.Law_pages.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Law_pages.setAutoFillBackground(False)
        self.Law_pages.setObjectName(_fromUtf8("Law_pages"))
        self.page = QtGui.QWidget()
        self.page.setObjectName(_fromUtf8("page"))
        self.gridLayout_3 = QtGui.QGridLayout(self.page)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.b_OK_page1 = QtGui.QDialogButtonBox(self.page)
        self.b_OK_page1.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.b_OK_page1.setStandardButtons(QtGui.QDialogButtonBox.Ok)
        self.b_OK_page1.setObjectName(_fromUtf8("b_OK_page1"))
        self.gridLayout_3.addWidget(self.b_OK_page1, 1, 4, 1, 1)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.comboBox_Name_law = QtGui.QComboBox(self.page)
        self.comboBox_Name_law.setObjectName(_fromUtf8("comboBox_Name_law"))
        self.gridLayout.addWidget(self.comboBox_Name_law, 0, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 5, 0, 1, 1)
        self.b_new = QtGui.QPushButton(self.page)
        self.b_new.setObjectName(_fromUtf8("b_new"))
        self.gridLayout.addWidget(self.b_new, 4, 1, 1, 1)
        self.b_delete = QtGui.QPushButton(self.page)
        self.b_delete.setObjectName(_fromUtf8("b_delete"))
        self.gridLayout.addWidget(self.b_delete, 4, 2, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 50, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        self.gridLayout.addItem(spacerItem1, 1, 0, 1, 1)
        self.label = QtGui.QLabel(self.page)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.b_edit = QtGui.QPushButton(self.page)
        self.b_edit.setObjectName(_fromUtf8("b_edit"))
        self.gridLayout.addWidget(self.b_edit, 4, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(100, 20, QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 3, 0, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(100, 20, QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 3, 1, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(100, 20, QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 3, 2, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 0, 1, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(75, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem5, 0, 0, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem6, 0, 4, 1, 1)
        self.Law_pages.addWidget(self.page)
        self.page_2 = QtGui.QWidget()
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.gridLayout_4 = QtGui.QGridLayout(self.page_2)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_2 = QtGui.QLabel(self.page_2)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout.addWidget(self.label_2)
        self.Name_edit = QtGui.QLineEdit(self.page_2)
        self.Name_edit.setObjectName(_fromUtf8("Name_edit"))
        self.horizontalLayout.addWidget(self.Name_edit)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem7)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.Table_laws = QtGui.QTableWidget(self.page_2)
        self.Table_laws.setObjectName(_fromUtf8("Table_laws"))
        self.Table_laws.setColumnCount(3)
        self.Table_laws.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.Table_laws.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.Table_laws.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.Table_laws.setHorizontalHeaderItem(2, item)
        self.verticalLayout.addWidget(self.Table_laws)
        self.b_OK_page2 = QtGui.QDialogButtonBox(self.page_2)
        self.b_OK_page2.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.b_OK_page2.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.b_OK_page2.setCenterButtons(False)
        self.b_OK_page2.setObjectName(_fromUtf8("b_OK_page2"))
        self.verticalLayout.addWidget(self.b_OK_page2)
        self.gridLayout_4.addLayout(self.verticalLayout, 0, 1, 1, 1)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        spacerItem8 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem8)
        self.b_add_line = QtGui.QPushButton(self.page_2)
        self.b_add_line.setObjectName(_fromUtf8("b_add_line"))
        self.verticalLayout_2.addWidget(self.b_add_line)
        self.b_delete_line = QtGui.QPushButton(self.page_2)
        self.b_delete_line.setObjectName(_fromUtf8("b_delete_line"))
        self.verticalLayout_2.addWidget(self.b_delete_line)
        spacerItem9 = QtGui.QSpacerItem(20, 23, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        self.verticalLayout_2.addItem(spacerItem9)
        self.gridLayout_4.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.Law_pages.addWidget(self.page_2)
        self.gridLayout_2.addWidget(self.Law_pages, 0, 0, 1, 1)
        self.actionB_edit = QtGui.QAction(TracerLaws)
        self.actionB_edit.setObjectName(_fromUtf8("actionB_edit"))
        self.actionComboBox_Name_law = QtGui.QAction(TracerLaws)
        self.actionComboBox_Name_law.setObjectName(_fromUtf8("actionComboBox_Name_law"))
        self.actionB_OK_page1 = QtGui.QAction(TracerLaws)
        self.actionB_OK_page1.setObjectName(_fromUtf8("actionB_OK_page1"))
        self.actionB_OK_page2 = QtGui.QAction(TracerLaws)
        self.actionB_OK_page2.setObjectName(_fromUtf8("actionB_OK_page2"))
        self.actionTable_laws = QtGui.QAction(TracerLaws)
        self.actionTable_laws.setObjectName(_fromUtf8("actionTable_laws"))
        self.actionName_edit = QtGui.QAction(TracerLaws)
        self.actionName_edit.setObjectName(_fromUtf8("actionName_edit"))
        self.actionLaw_pages = QtGui.QAction(TracerLaws)
        self.actionLaw_pages.setObjectName(_fromUtf8("actionLaw_pages"))
        self.actionB_new = QtGui.QAction(TracerLaws)
        self.actionB_new.setObjectName(_fromUtf8("actionB_new"))
        self.actionB_delete = QtGui.QAction(TracerLaws)
        self.actionB_delete.setObjectName(_fromUtf8("actionB_delete"))

        self.retranslateUi(TracerLaws)
        QtCore.QObject.connect(self.b_edit, QtCore.SIGNAL(_fromUtf8("clicked()")), self.actionB_edit.trigger)
        QtCore.QObject.connect(self.b_new, QtCore.SIGNAL(_fromUtf8("clicked()")), self.actionB_new.trigger)
        QtCore.QObject.connect(self.b_delete, QtCore.SIGNAL(_fromUtf8("clicked()")), self.actionB_delete.trigger)
        QtCore.QMetaObject.connectSlotsByName(TracerLaws)

    def retranslateUi(self, TracerLaws):
        TracerLaws.setWindowTitle(_translate("TracerLaws", "Tracer Laws", None))
        self.b_new.setText(_translate("TracerLaws", "New", None))
        self.b_delete.setText(_translate("TracerLaws", "Delete", None))
        self.label.setText(_translate("TracerLaws", "Law Names :", None))
        self.b_edit.setText(_translate("TracerLaws", "Edit", None))
        self.label_2.setText(_translate("TracerLaws", "Law Names :", None))
        item = self.Table_laws.horizontalHeaderItem(0)
        item.setText(_translate("TracerLaws", "Time", None))
        item = self.Table_laws.horizontalHeaderItem(1)
        item.setText(_translate("TracerLaws", "C° TRA1", None))
        item = self.Table_laws.horizontalHeaderItem(2)
        item.setText(_translate("TracerLaws", "C° TRA2", None))
        self.b_add_line.setText(_translate("TracerLaws", "Add Line", None))
        self.b_delete_line.setText(_translate("TracerLaws", "Delete Line", None))
        self.actionB_edit.setText(_translate("TracerLaws", "b_edit", None))
        self.actionComboBox_Name_law.setText(_translate("TracerLaws", "comboBox_Name_law", None))
        self.actionB_OK_page1.setText(_translate("TracerLaws", "b_OK_page1", None))
        self.actionB_OK_page2.setText(_translate("TracerLaws", "b_OK_page2", None))
        self.actionTable_laws.setText(_translate("TracerLaws", "Table_laws", None))
        self.actionName_edit.setText(_translate("TracerLaws", "Name_edit", None))
        self.actionLaw_pages.setText(_translate("TracerLaws", "Law_pages", None))
        self.actionB_new.setText(_translate("TracerLaws", "b_new", None))
        self.actionB_delete.setText(_translate("TracerLaws", "b_delete", None))

