# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_water_quality.ui'
#
# Created: Wed Dec 20 17:08:46 2017
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Parameter_water_q(object):
    def setupUi(self, Parameter_water_q):
        Parameter_water_q.setObjectName(_fromUtf8("Parameter_water_q"))
        Parameter_water_q.resize(853, 607)
        self.gridLayout_2 = QtGui.QGridLayout(Parameter_water_q)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.buttonBox = QtGui.QDialogButtonBox(Parameter_water_q)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout_2.addWidget(self.buttonBox, 2, 0, 1, 1)
        self.WaterQ = QtGui.QTabWidget(Parameter_water_q)
        self.WaterQ.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.WaterQ.setObjectName(_fromUtf8("WaterQ"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tab)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.comboBox = QtGui.QComboBox(self.tab)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboBox, 1, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 1, 1, 1)
        self.label = QtGui.QLabel(self.tab)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.checkBox = QtGui.QCheckBox(self.tab)
        self.checkBox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.gridLayout.addWidget(self.checkBox, 0, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.tab)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 2, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 0, 2, 1, 1)
        self.spinBox = QtGui.QSpinBox(self.tab)
        self.spinBox.setMinimum(1)
        self.spinBox.setMaximum(10)
        self.spinBox.setObjectName(_fromUtf8("spinBox"))
        self.gridLayout.addWidget(self.spinBox, 2, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.tableWidget = QtGui.QTableWidget(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setWordWrap(False)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(150)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(50)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(False)
        self.tableWidget.verticalHeader().setSortIndicatorShown(False)
        self.tableWidget.verticalHeader().setStretchLastSection(False)
        self.gridLayout_3.addWidget(self.tableWidget, 1, 0, 1, 1)
        self.WaterQ.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.gridLayout_4 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.tableWidget_2 = QtGui.QTableWidget(self.tab_2)
        self.tableWidget_2.setObjectName(_fromUtf8("tableWidget_2"))
        self.tableWidget_2.setColumnCount(3)
        self.tableWidget_2.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        self.gridLayout_4.addWidget(self.tableWidget_2, 0, 0, 1, 1)
        self.WaterQ.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.gridLayout_7 = QtGui.QGridLayout(self.tab_3)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.radioButton_6 = QtGui.QRadioButton(self.tab_3)
        self.radioButton_6.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.radioButton_6.setObjectName(_fromUtf8("radioButton_6"))
        self.gridLayout_5.addWidget(self.radioButton_6, 8, 1, 1, 1)
        self.radioButton_7 = QtGui.QRadioButton(self.tab_3)
        self.radioButton_7.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.radioButton_7.setObjectName(_fromUtf8("radioButton_7"))
        self.gridLayout_5.addWidget(self.radioButton_7, 4, 2, 1, 1)
        self.comboBox_4 = QtGui.QComboBox(self.tab_3)
        self.comboBox_4.setEnabled(False)
        self.comboBox_4.setObjectName(_fromUtf8("comboBox_4"))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.gridLayout_5.addWidget(self.comboBox_4, 2, 1, 1, 1)
        self.radioButton_8 = QtGui.QRadioButton(self.tab_3)
        self.radioButton_8.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.radioButton_8.setObjectName(_fromUtf8("radioButton_8"))
        self.gridLayout_5.addWidget(self.radioButton_8, 5, 2, 1, 1)
        self.label_3 = QtGui.QLabel(self.tab_3)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_5.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.tab_3)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_5.addWidget(self.label_5, 1, 2, 1, 1)
        self.comboBox_3 = QtGui.QComboBox(self.tab_3)
        self.comboBox_3.setObjectName(_fromUtf8("comboBox_3"))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.gridLayout_5.addWidget(self.comboBox_3, 1, 3, 1, 1)
        self.label_8 = QtGui.QLabel(self.tab_3)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_5.addWidget(self.label_8, 3, 0, 1, 1)
        self.spinBox_2 = QtGui.QSpinBox(self.tab_3)
        self.spinBox_2.setMinimum(1)
        self.spinBox_2.setMaximum(999999999)
        self.spinBox_2.setProperty("value", 1)
        self.spinBox_2.setObjectName(_fromUtf8("spinBox_2"))
        self.gridLayout_5.addWidget(self.spinBox_2, 0, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.tab_3)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_5.addWidget(self.label_4, 1, 0, 1, 1)
        self.comboBox_2 = QtGui.QComboBox(self.tab_3)
        self.comboBox_2.setObjectName(_fromUtf8("comboBox_2"))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.gridLayout_5.addWidget(self.comboBox_2, 1, 1, 1, 1)
        self.radioButton = QtGui.QRadioButton(self.tab_3)
        self.radioButton.setObjectName(_fromUtf8("radioButton"))
        self.gridLayout_5.addWidget(self.radioButton, 3, 1, 1, 1)
        self.radioButton_3 = QtGui.QRadioButton(self.tab_3)
        self.radioButton_3.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.radioButton_3.setObjectName(_fromUtf8("radioButton_3"))
        self.gridLayout_5.addWidget(self.radioButton_3, 5, 1, 1, 1)
        self.radioButton_11 = QtGui.QRadioButton(self.tab_3)
        self.radioButton_11.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.radioButton_11.setObjectName(_fromUtf8("radioButton_11"))
        self.gridLayout_5.addWidget(self.radioButton_11, 8, 2, 1, 1)
        self.radioButton_4 = QtGui.QRadioButton(self.tab_3)
        self.radioButton_4.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.radioButton_4.setObjectName(_fromUtf8("radioButton_4"))
        self.gridLayout_5.addWidget(self.radioButton_4, 6, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.tab_3)
        self.label_6.setEnabled(False)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_5.addWidget(self.label_6, 2, 0, 1, 1)
        self.radioButton_10 = QtGui.QRadioButton(self.tab_3)
        self.radioButton_10.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.radioButton_10.setObjectName(_fromUtf8("radioButton_10"))
        self.gridLayout_5.addWidget(self.radioButton_10, 7, 2, 1, 1)
        self.radioButton_2 = QtGui.QRadioButton(self.tab_3)
        self.radioButton_2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.radioButton_2.setObjectName(_fromUtf8("radioButton_2"))
        self.gridLayout_5.addWidget(self.radioButton_2, 4, 1, 1, 1)
        self.radioButton_5 = QtGui.QRadioButton(self.tab_3)
        self.radioButton_5.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.radioButton_5.setObjectName(_fromUtf8("radioButton_5"))
        self.gridLayout_5.addWidget(self.radioButton_5, 7, 1, 1, 1)
        self.doubleSpinBox = QtGui.QDoubleSpinBox(self.tab_3)
        self.doubleSpinBox.setEnabled(False)
        self.doubleSpinBox.setDecimals(4)
        self.doubleSpinBox.setMinimum(-1000000000.0)
        self.doubleSpinBox.setMaximum(1000000000.0)
        self.doubleSpinBox.setProperty("value", 0.0)
        self.doubleSpinBox.setObjectName(_fromUtf8("doubleSpinBox"))
        self.gridLayout_5.addWidget(self.doubleSpinBox, 2, 3, 1, 1)
        self.label_7 = QtGui.QLabel(self.tab_3)
        self.label_7.setEnabled(False)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_5.addWidget(self.label_7, 2, 2, 1, 1)
        self.radioButton_9 = QtGui.QRadioButton(self.tab_3)
        self.radioButton_9.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.radioButton_9.setObjectName(_fromUtf8("radioButton_9"))
        self.gridLayout_5.addWidget(self.radioButton_9, 6, 2, 1, 1)
        self.doubleSpinBox_2 = QtGui.QDoubleSpinBox(self.tab_3)
        self.doubleSpinBox_2.setEnabled(False)
        self.doubleSpinBox_2.setMinimum(-1000000000.0)
        self.doubleSpinBox_2.setMaximum(1000000000.0)
        self.doubleSpinBox_2.setObjectName(_fromUtf8("doubleSpinBox_2"))
        self.gridLayout_5.addWidget(self.doubleSpinBox_2, 3, 2, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_5)
        self.tableWidget_3 = QtGui.QTableWidget(self.tab_3)
        self.tableWidget_3.setObjectName(_fromUtf8("tableWidget_3"))
        self.tableWidget_3.setColumnCount(3)
        self.tableWidget_3.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(2, item)
        self.tableWidget_3.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_2.addWidget(self.tableWidget_3)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.pushButton = QtGui.QPushButton(self.tab_3)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout_2.addWidget(self.pushButton)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.pushButton_2 = QtGui.QPushButton(self.tab_3)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.gridLayout_7.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.WaterQ.addTab(self.tab_3, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.gridLayout_6 = QtGui.QGridLayout(self.tab_5)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.impressionGeometrie = QtGui.QCheckBox(self.tab_5)
        self.impressionGeometrie.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.impressionGeometrie.setObjectName(_fromUtf8("impressionGeometrie"))
        self.verticalLayout.addWidget(self.impressionGeometrie)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem6)
        self.impressionPlanimetrage = QtGui.QCheckBox(self.tab_5)
        self.impressionPlanimetrage.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.impressionPlanimetrage.setObjectName(_fromUtf8("impressionPlanimetrage"))
        self.verticalLayout.addWidget(self.impressionPlanimetrage)
        spacerItem7 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem7)
        self.impressionReseau = QtGui.QCheckBox(self.tab_5)
        self.impressionReseau.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.impressionReseau.setObjectName(_fromUtf8("impressionReseau"))
        self.verticalLayout.addWidget(self.impressionReseau)
        spacerItem8 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem8)
        self.impressionLoiHydraulique = QtGui.QCheckBox(self.tab_5)
        self.impressionLoiHydraulique.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.impressionLoiHydraulique.setObjectName(_fromUtf8("impressionLoiHydraulique"))
        self.verticalLayout.addWidget(self.impressionLoiHydraulique)
        self.gridLayout_6.addLayout(self.verticalLayout, 0, 0, 1, 1)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem9, 0, 1, 1, 1)
        spacerItem10 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem10, 1, 0, 1, 1)
        self.WaterQ.addTab(self.tab_5, _fromUtf8(""))
        self.gridLayout_2.addWidget(self.WaterQ, 1, 0, 1, 1)

        self.retranslateUi(Parameter_water_q)
        self.WaterQ.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Parameter_water_q)

    def retranslateUi(self, Parameter_water_q):
        Parameter_water_q.setWindowTitle(_translate("Parameter_water_q", "Parameters Water Quality", None))
        self.comboBox.setItemText(0, _translate("Parameter_water_q", "TRANSPORT_PUR", None))
        self.comboBox.setItemText(1, _translate("Parameter_water_q", "O2", None))
        self.comboBox.setItemText(2, _translate("Parameter_water_q", "BIOMASS", None))
        self.comboBox.setItemText(3, _translate("Parameter_water_q", "EUTRO", None))
        self.comboBox.setItemText(4, _translate("Parameter_water_q", "MICROPOLE", None))
        self.comboBox.setItemText(5, _translate("Parameter_water_q", "THERMIC", None))
        self.label.setText(_translate("Parameter_water_q", "Water quality module : ", None))
        self.checkBox.setText(_translate("Parameter_water_q", "Activation of the water quality module", None))
        self.label_2.setText(_translate("Parameter_water_q", "Number of constituents : ", None))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Parameter_water_q", "Names of constituents", None))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Parameter_water_q", "Properties", None))
        self.WaterQ.setTabText(self.WaterQ.indexOf(self.tab), _translate("Parameter_water_q", "Choice of the water quality module", None))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("Parameter_water_q", "N° Bief", None))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("Parameter_water_q", "Abscisca", None))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("Parameter_water_q", "C°TRA1", None))
        self.WaterQ.setTabText(self.WaterQ.indexOf(self.tab_2), _translate("Parameter_water_q", "Initial Concentrations", None))
        self.radioButton_6.setText(_translate("Parameter_water_q", "Seo & Cheong (1998)", None))
        self.radioButton_7.setText(_translate("Parameter_water_q", "Fisher (1975)", None))
        self.comboBox_4.setItemText(0, _translate("Parameter_water_q", "Yes", None))
        self.comboBox_4.setItemText(1, _translate("Parameter_water_q", "No", None))
        self.radioButton_8.setText(_translate("Parameter_water_q", "Isawa & Aga (1991)", None))
        self.label_3.setText(_translate("Parameter_water_q", "Frequency for coupling :", None))
        self.label_5.setText(_translate("Parameter_water_q", "Scheme order :", None))
        self.comboBox_3.setItemText(0, _translate("Parameter_water_q", "1", None))
        self.comboBox_3.setItemText(1, _translate("Parameter_water_q", "2", None))
        self.label_8.setText(_translate("Parameter_water_q", "Diffusion method :", None))
        self.label_4.setText(_translate("Parameter_water_q", "Convection method :", None))
        self.comboBox_2.setItemText(0, _translate("Parameter_water_q", "HYP1FA fnc", None))
        self.comboBox_2.setItemText(1, _translate("Parameter_water_q", "HYP1FA fc", None))
        self.comboBox_2.setItemText(2, _translate("Parameter_water_q", "FV", None))
        self.radioButton.setText(_translate("Parameter_water_q", "Constant diffussion coef. :", None))
        self.radioButton_3.setText(_translate("Parameter_water_q", "Liu (1977)", None))
        self.radioButton_11.setText(_translate("Parameter_water_q", "Deng & al. (2001)", None))
        self.radioButton_4.setText(_translate("Parameter_water_q", "McQuivey & Keefer", None))
        self.label_6.setText(_translate("Parameter_water_q", "Slope limiter", None))
        self.radioButton_10.setText(_translate("Parameter_water_q", "Koussis & Rodriguez-Mirasol (1998)", None))
        self.radioButton_2.setText(_translate("Parameter_water_q", "Elder (1959)", None))
        self.radioButton_5.setText(_translate("Parameter_water_q", "Magazine & al. (1988)", None))
        self.label_7.setText(_translate("Parameter_water_q", "Prameter W", None))
        self.radioButton_9.setText(_translate("Parameter_water_q", "Kashefipur & Falconer (2002)", None))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("Parameter_water_q", "Tracer name", None))
        item = self.tableWidget_3.horizontalHeaderItem(1)
        item.setText(_translate("Parameter_water_q", "Diffusion", None))
        item = self.tableWidget_3.horizontalHeaderItem(2)
        item.setText(_translate("Parameter_water_q", "Convection", None))
        self.pushButton.setText(_translate("Parameter_water_q", "Physical parameters", None))
        self.pushButton_2.setText(_translate("Parameter_water_q", "Meteo parameters", None))
        self.WaterQ.setTabText(self.WaterQ.indexOf(self.tab_3), _translate("Parameter_water_q", "General Parameters", None))
        self.impressionGeometrie.setText(_translate("Parameter_water_q", "Initial Concentration", None))
        self.impressionPlanimetrage.setText(_translate("Parameter_water_q", "Tracer law used", None))
        self.impressionReseau.setText(_translate("Parameter_water_q", "Concentrations", None))
        self.impressionLoiHydraulique.setText(_translate("Parameter_water_q", "Constituants balance", None))
        self.WaterQ.setTabText(self.WaterQ.indexOf(self.tab_5), _translate("Parameter_water_q", "Results", None))

