# -*- coding: utf-8 -*-

"""
/***************************************************************************
Name                 :  MasPlug
Description          : Graph class
Date                 : Aout 2017

email                :
***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""


from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)
try:
    from matplotlib.backends.backend_qt4agg\
        import NavigationToolbar2QTAgg as NavigationToolbar

except:
    from matplotlib.backends.backend_qt4agg \
        import NavigationToolbar2QT as NavigationToolbar
class Ui_ProfilGraph(object):
    def setupUi(self, ProfilGraph):
        ProfilGraph.setObjectName(_fromUtf8("ProfilGraph"))
        ProfilGraph.resize(1079, 850)
        self.gridLayout_2 = QtGui.QGridLayout(ProfilGraph)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.bt_reculTot = QtGui.QPushButton(ProfilGraph)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_reculTot.sizePolicy().hasHeightForWidth())
        self.bt_reculTot.setSizePolicy(sizePolicy)
        self.bt_reculTot.setDefault(False)
        self.bt_reculTot.setObjectName(_fromUtf8("bt_reculTot"))
        self.horizontalLayout_2.addWidget(self.bt_reculTot)
        self.bt_recul = QtGui.QPushButton(ProfilGraph)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_recul.sizePolicy().hasHeightForWidth())
        self.bt_recul.setSizePolicy(sizePolicy)
        self.bt_recul.setObjectName(_fromUtf8("bt_recul"))
        self.horizontalLayout_2.addWidget(self.bt_recul)
        self.bt_av = QtGui.QPushButton(ProfilGraph)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_av.sizePolicy().hasHeightForWidth())
        self.bt_av.setSizePolicy(sizePolicy)
        self.bt_av.setObjectName(_fromUtf8("bt_av"))
        self.horizontalLayout_2.addWidget(self.bt_av)
        self.bt_avTot = QtGui.QPushButton(ProfilGraph)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_avTot.sizePolicy().hasHeightForWidth())
        self.bt_avTot.setSizePolicy(sizePolicy)
        self.bt_avTot.setObjectName(_fromUtf8("bt_avTot"))
        self.horizontalLayout_2.addWidget(self.bt_avTot)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(ProfilGraph)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(True)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.label_Title = QtGui.QLabel(ProfilGraph)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_Title.setFont(font)
        self.label_Title.setObjectName(_fromUtf8("label_Title"))
        self.horizontalLayout.addWidget(self.label_Title)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_4.addLayout(self.verticalLayout_3)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.bt_topo_del = QtGui.QPushButton(ProfilGraph)
        self.bt_topo_del.setObjectName(_fromUtf8("bt_topo_del"))
        self.gridLayout.addWidget(self.bt_topo_del, 2, 1, 1, 1)
        self.bt_topo_load = QtGui.QPushButton(ProfilGraph)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_topo_load.sizePolicy().hasHeightForWidth())
        self.bt_topo_load.setSizePolicy(sizePolicy)
        self.bt_topo_load.setObjectName(_fromUtf8("bt_topo_load"))
        self.gridLayout.addWidget(self.bt_topo_load, 2, 0, 1, 1)
        self.bt_profil_filter = QtGui.QPushButton(ProfilGraph)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_profil_filter.sizePolicy().hasHeightForWidth())
        self.bt_profil_filter.setSizePolicy(sizePolicy)
        self.bt_profil_filter.setObjectName(_fromUtf8("bt_profil_filter"))
        self.gridLayout.addWidget(self.bt_profil_filter, 3, 1, 1, 1)
        self.bt_profil_save = QtGui.QPushButton(ProfilGraph)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_profil_save.sizePolicy().hasHeightForWidth())
        self.bt_profil_save.setSizePolicy(sizePolicy)
        self.bt_profil_save.setObjectName(_fromUtf8("bt_profil_save"))
        self.gridLayout.addWidget(self.bt_profil_save, 3, 0, 1, 1)
        self.bt_profil_del = QtGui.QPushButton(ProfilGraph)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_profil_del.sizePolicy().hasHeightForWidth())
        self.bt_profil_del.setSizePolicy(sizePolicy)
        self.bt_profil_del.setObjectName(_fromUtf8("bt_profil_del"))
        self.gridLayout.addWidget(self.bt_profil_del, 3, 2, 1, 1)
        self.bt_img_load = QtGui.QPushButton(ProfilGraph)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_img_load.sizePolicy().hasHeightForWidth())
        self.bt_img_load.setSizePolicy(sizePolicy)
        self.bt_img_load.setObjectName(_fromUtf8("bt_img_load"))
        self.gridLayout.addWidget(self.bt_img_load, 2, 4, 1, 1)
        self.bt_topo_save = QtGui.QPushButton(ProfilGraph)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_topo_save.sizePolicy().hasHeightForWidth())
        self.bt_topo_save.setSizePolicy(sizePolicy)
        self.bt_topo_save.setObjectName(_fromUtf8("bt_topo_save"))
        self.gridLayout.addWidget(self.bt_topo_save, 2, 2, 1, 1)
        self.horizontalLayout_4.addLayout(self.gridLayout)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.btTools_point_selection = QtGui.QToolButton(ProfilGraph)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/MascPlug/icones/select.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btTools_point_selection.setIcon(icon)
        self.btTools_point_selection.setIconSize(QtCore.QSize(24, 24))
        self.btTools_point_selection.setCheckable(True)
        self.btTools_point_selection.setObjectName(_fromUtf8("btTools_point_selection"))
        self.horizontalLayout_5.addWidget(self.btTools_point_selection)
        self.btTools_zone_selection = QtGui.QToolButton(ProfilGraph)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/MascPlug/icones/select_zone.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btTools_zone_selection.setIcon(icon1)
        self.btTools_zone_selection.setIconSize(QtCore.QSize(24, 24))
        self.btTools_zone_selection.setCheckable(True)
        self.btTools_zone_selection.setObjectName(_fromUtf8("btTools_zone_selection"))
        self.horizontalLayout_5.addWidget(self.btTools_zone_selection)
        self.btTools_profil_translation = QtGui.QToolButton(ProfilGraph)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/MascPlug/icones/deplace_profil.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btTools_profil_translation.setIcon(icon2)
        self.btTools_profil_translation.setIconSize(QtCore.QSize(24, 24))
        self.btTools_profil_translation.setCheckable(True)
        self.btTools_profil_translation.setChecked(False)
        self.btTools_profil_translation.setObjectName(_fromUtf8("btTools_profil_translation"))
        self.horizontalLayout_5.addWidget(self.btTools_profil_translation)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.bt_l_stok = QtGui.QPushButton(ProfilGraph)
        self.bt_l_stok.setObjectName(_fromUtf8("bt_l_stok"))
        self.horizontalLayout_5.addWidget(self.bt_l_stok)
        self.bt_minor_bed = QtGui.QPushButton(ProfilGraph)
        self.bt_minor_bed.setObjectName(_fromUtf8("bt_minor_bed"))
        self.horizontalLayout_5.addWidget(self.bt_minor_bed)
        self.bt_r_stok = QtGui.QPushButton(ProfilGraph)
        self.bt_r_stok.setObjectName(_fromUtf8("bt_r_stok"))
        self.horizontalLayout_5.addWidget(self.bt_r_stok)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        # **************************************


        self.verticalLayout_99 = QtGui.QVBoxLayout()
        self.verticalLayout_99.setObjectName(_fromUtf8("verticalLayout_99"))
        self.toolbar = NavigationToolbar(ProfilGraph.canvas, ProfilGraph)
        self.verticalLayout_99.addWidget(ProfilGraph.canvas)
        self.verticalLayout_99.addWidget(self.toolbar)
        self.horizontalLayout_3.addLayout(self.verticalLayout_99)
        # **************************************

        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.tableWidget = QtGui.QTableWidget(ProfilGraph)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.verticalLayout_2.addWidget(self.tableWidget)
        self.bt_add_point = QtGui.QPushButton(ProfilGraph)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(255)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_add_point.sizePolicy().hasHeightForWidth())
        self.bt_add_point.setSizePolicy(sizePolicy)
        self.bt_add_point.setObjectName(_fromUtf8("bt_add_point"))
        self.verticalLayout_2.addWidget(self.bt_add_point)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.gridLayout_2.addLayout(self.verticalLayout_4, 0, 0, 1, 1)
        self.actionBt_add_point = QtGui.QAction(ProfilGraph)
        self.actionBt_add_point.setObjectName(_fromUtf8("actionBt_add_point"))
        self.actionBt_reculTot = QtGui.QAction(ProfilGraph)
        self.actionBt_reculTot.setObjectName(_fromUtf8("actionBt_reculTot"))
        self.actionBt_recul = QtGui.QAction(ProfilGraph)
        self.actionBt_recul.setObjectName(_fromUtf8("actionBt_recul"))
        self.actionBt_av = QtGui.QAction(ProfilGraph)
        self.actionBt_av.setObjectName(_fromUtf8("actionBt_av"))
        self.actionBt_avTot = QtGui.QAction(ProfilGraph)
        self.actionBt_avTot.setObjectName(_fromUtf8("actionBt_avTot"))
        self.actionBt_topo_save = QtGui.QAction(ProfilGraph)
        self.actionBt_topo_save.setObjectName(_fromUtf8("actionBt_topo_save"))
        self.actionBt_topo_load = QtGui.QAction(ProfilGraph)
        self.actionBt_topo_load.setObjectName(_fromUtf8("actionBt_topo_load"))
        self.actionBt_img_load = QtGui.QAction(ProfilGraph)
        self.actionBt_img_load.setObjectName(_fromUtf8("actionBt_img_load"))
        self.actionBt_profil_save = QtGui.QAction(ProfilGraph)
        self.actionBt_profil_save.setObjectName(_fromUtf8("actionBt_profil_save"))
        self.actionBt_profil_filter = QtGui.QAction(ProfilGraph)
        self.actionBt_profil_filter.setObjectName(_fromUtf8("actionBt_profil_filter"))
        self.actionBt_profil_del = QtGui.QAction(ProfilGraph)
        self.actionBt_profil_del.setObjectName(_fromUtf8("actionBt_profil_del"))
        self.actionBtTools_profil_translation = QtGui.QAction(ProfilGraph)
        self.actionBtTools_profil_translation.setObjectName(_fromUtf8("actionBtTools_profil_translation"))
        self.actionBtTools_zone_selection = QtGui.QAction(ProfilGraph)
        self.actionBtTools_zone_selection.setCheckable(False)
        self.actionBtTools_zone_selection.setObjectName(_fromUtf8("actionBtTools_zone_selection"))
        self.actionBtTools_point_selection = QtGui.QAction(ProfilGraph)
        self.actionBtTools_point_selection.setCheckable(False)
        self.actionBtTools_point_selection.setObjectName(_fromUtf8("actionBtTools_point_selection"))
        self.actionBt_minor_bed = QtGui.QAction(ProfilGraph)
        self.actionBt_minor_bed.setObjectName(_fromUtf8("actionBt_minor_bed"))
        self.actionBt_r_stok = QtGui.QAction(ProfilGraph)
        self.actionBt_r_stok.setObjectName(_fromUtf8("actionBt_r_stok"))
        self.actionBt_l_stok = QtGui.QAction(ProfilGraph)
        self.actionBt_l_stok.setObjectName(_fromUtf8("actionBt_l_stok"))
        self.actionBt_topo_del = QtGui.QAction(ProfilGraph)
        self.actionBt_topo_del.setObjectName(_fromUtf8("actionBt_topo_del"))

        self.retranslateUi(ProfilGraph)
        QtCore.QObject.connect(self.bt_add_point, QtCore.SIGNAL(_fromUtf8("clicked()")), self.actionBt_add_point.trigger)
        QtCore.QObject.connect(self.bt_recul, QtCore.SIGNAL(_fromUtf8("clicked()")), self.actionBt_recul.trigger)
        QtCore.QObject.connect(self.bt_reculTot, QtCore.SIGNAL(_fromUtf8("clicked()")), self.actionBt_reculTot.trigger)
        QtCore.QObject.connect(self.bt_av, QtCore.SIGNAL(_fromUtf8("clicked()")), self.actionBt_av.trigger)
        QtCore.QObject.connect(self.bt_avTot, QtCore.SIGNAL(_fromUtf8("clicked()")), self.actionBt_avTot.trigger)
        QtCore.QObject.connect(self.bt_topo_load, QtCore.SIGNAL(_fromUtf8("clicked()")), self.actionBt_topo_load.trigger)
        QtCore.QObject.connect(self.bt_img_load, QtCore.SIGNAL(_fromUtf8("clicked()")), self.actionBt_img_load.trigger)
        QtCore.QObject.connect(self.bt_profil_filter, QtCore.SIGNAL(_fromUtf8("clicked()")), self.actionBt_profil_filter.trigger)
        QtCore.QObject.connect(self.bt_profil_del, QtCore.SIGNAL(_fromUtf8("clicked()")), self.actionBt_profil_del.trigger)
        QtCore.QObject.connect(self.bt_profil_save, QtCore.SIGNAL(_fromUtf8("clicked()")), self.actionBt_profil_save.trigger)
        QtCore.QObject.connect(self.btTools_profil_translation, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.actionBtTools_profil_translation.trigger)
        QtCore.QObject.connect(self.btTools_zone_selection, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.actionBtTools_zone_selection.trigger)
        QtCore.QObject.connect(self.btTools_point_selection, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.actionBtTools_point_selection.trigger)
        QtCore.QObject.connect(self.bt_minor_bed, QtCore.SIGNAL(_fromUtf8("clicked()")), self.actionBt_minor_bed.trigger)
        QtCore.QObject.connect(self.bt_l_stok, QtCore.SIGNAL(_fromUtf8("clicked()")), self.actionBt_l_stok.trigger)
        QtCore.QObject.connect(self.bt_r_stok, QtCore.SIGNAL(_fromUtf8("clicked()")), self.actionBt_r_stok.trigger)
        QtCore.QObject.connect(self.bt_topo_del, QtCore.SIGNAL(_fromUtf8("clicked()")), self.actionBt_topo_del.trigger)
        QtCore.QObject.connect(self.bt_topo_save, QtCore.SIGNAL(_fromUtf8("clicked()")), self.actionBt_topo_save.trigger)
        QtCore.QMetaObject.connectSlotsByName(ProfilGraph)

    def retranslateUi(self, ProfilGraph):
        ProfilGraph.setWindowTitle(_translate("ProfilGraph", "Profile Editor", None))
        self.bt_reculTot.setText(_translate("ProfilGraph", "<<", None))
        self.bt_recul.setText(_translate("ProfilGraph", "<", None))
        self.bt_av.setText(_translate("ProfilGraph", ">", None))
        self.bt_avTot.setText(_translate("ProfilGraph", ">>", None))
        self.label.setText(_translate("ProfilGraph", "Title :", None))
        self.label_Title.setText(_translate("ProfilGraph", "Toto", None))
        self.bt_topo_del.setText(_translate("ProfilGraph", "Topo. Delete", None))
        self.bt_topo_load.setText(_translate("ProfilGraph", "Topo. Import", None))
        self.bt_profil_filter.setText(_translate("ProfilGraph", "Profil Filter", None))
        self.bt_profil_save.setText(_translate("ProfilGraph", "Profil Save", None))
        self.bt_profil_del.setText(_translate("ProfilGraph", "Profil Delete", None))
        self.bt_img_load.setText(_translate("ProfilGraph", "Picture Import", None))
        self.bt_topo_save.setText(_translate("ProfilGraph", "Topo. Save", None))
        self.btTools_point_selection.setText(_translate("ProfilGraph", "Point Selection", None))
        self.btTools_zone_selection.setText(_translate("ProfilGraph", "Zone Selection", None))
        self.btTools_profil_translation.setText(_translate("ProfilGraph", "Profil Translation", None))
        self.bt_l_stok.setText(_translate("ProfilGraph", "Left Storage Area", None))
        self.bt_minor_bed.setText(_translate("ProfilGraph", "Minor River Bed", None))
        self.bt_r_stok.setText(_translate("ProfilGraph", "Right Storage Area", None))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("ProfilGraph", "X", None))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("ProfilGraph", "Z", None))
        self.bt_add_point.setText(_translate("ProfilGraph", "Add point selection", None))
        self.actionBt_add_point.setText(_translate("ProfilGraph", "bt_add_point", None))
        self.actionBt_reculTot.setText(_translate("ProfilGraph", "bt_reculTot", None))
        self.actionBt_recul.setText(_translate("ProfilGraph", "bt_recul", None))
        self.actionBt_av.setText(_translate("ProfilGraph", "bt_av", None))
        self.actionBt_avTot.setText(_translate("ProfilGraph", "bt_avTot", None))
        self.actionBt_topo_save.setText(_translate("ProfilGraph", "bt_topo_save", None))
        self.actionBt_topo_load.setText(_translate("ProfilGraph", "bt_topo_load", None))
        self.actionBt_img_load.setText(_translate("ProfilGraph", "bt_img_load", None))
        self.actionBt_profil_save.setText(_translate("ProfilGraph", "bt_profil_save", None))
        self.actionBt_profil_filter.setText(_translate("ProfilGraph", "bt_profil_filter", None))
        self.actionBt_profil_del.setText(_translate("ProfilGraph", "bt_profil_del", None))
        self.actionBtTools_profil_translation.setText(_translate("ProfilGraph", "btTools_profil_translation", None))
        self.actionBtTools_zone_selection.setText(_translate("ProfilGraph", "btTools_zone_selection", None))
        self.actionBtTools_point_selection.setText(_translate("ProfilGraph", "btTools_point_selection", None))
        self.actionBt_minor_bed.setText(_translate("ProfilGraph", "bt_minor_bed", None))
        self.actionBt_r_stok.setText(_translate("ProfilGraph", "bt_r_stok", None))
        self.actionBt_l_stok.setText(_translate("ProfilGraph", "bt_l_stok", None))
        self.actionBt_topo_del.setText(_translate("ProfilGraph", "bt_topo_del", None))
