# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MascPlug_dialog_base.ui'
#
# Created: Wed Dec 20 16:41:34 2017
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MascPlug(object):
    def setupUi(self, MascPlug):
        MascPlug.setObjectName(_fromUtf8("MascPlug"))
        MascPlug.setEnabled(True)
        MascPlug.resize(859, 738)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/Mascaret/icones/icon_base.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MascPlug.setWindowIcon(icon)
        MascPlug.setIconSize(QtCore.QSize(24, 24))
        self.centralwidget = QtGui.QWidget(MascPlug)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.crsWidget = QgsProjectionSelectionWidget(self.centralwidget)
        self.crsWidget.setMinimumSize(QtCore.QSize(300, 0))
        self.crsWidget.setMaximumSize(QtCore.QSize(400, 16777215))
        self.crsWidget.setObjectName(_fromUtf8("crsWidget"))
        self.horizontalLayout.addWidget(self.crsWidget)
        self.gridLayout_2.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.textEdit = QtGui.QTextEdit(self.centralwidget)
        self.textEdit.setMouseTracking(False)
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.gridLayout_2.addWidget(self.textEdit, 0, 0, 1, 1)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.connsCbo = QtGui.QComboBox(self.centralwidget)
        self.connsCbo.setMinimumSize(QtCore.QSize(200, 0))
        self.connsCbo.setObjectName(_fromUtf8("connsCbo"))
        self.gridLayout.addWidget(self.connsCbo, 0, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 2, 1, 1)
        self.labelCurDatabase = QtGui.QLabel(self.centralwidget)
        self.labelCurDatabase.setObjectName(_fromUtf8("labelCurDatabase"))
        self.gridLayout.addWidget(self.labelCurDatabase, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 2, 0, 1, 1)
        MascPlug.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MascPlug)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 859, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        self.menuSetting = QtGui.QMenu(self.menuHelp)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/Mascaret/icones/options.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menuSetting.setIcon(icon1)
        self.menuSetting.setObjectName(_fromUtf8("menuSetting"))
        self.menu_Tools = QtGui.QMenu(self.menubar)
        self.menu_Tools.setObjectName(_fromUtf8("menu_Tools"))
        self.menuDB = QtGui.QMenu(self.menubar)
        self.menuDB.setObjectName(_fromUtf8("menuDB"))
        self.menuRun = QtGui.QMenu(self.menubar)
        self.menuRun.setObjectName(_fromUtf8("menuRun"))
        self.menuPost_Treatment = QtGui.QMenu(self.menubar)
        self.menuPost_Treatment.setObjectName(_fromUtf8("menuPost_Treatment"))
        self.menuWater_Quality = QtGui.QMenu(self.menubar)
        self.menuWater_Quality.setObjectName(_fromUtf8("menuWater_Quality"))
        MascPlug.setMenuBar(self.menubar)
        self.dbToolBar = QtGui.QToolBar(MascPlug)
        self.dbToolBar.setObjectName(_fromUtf8("dbToolBar"))
        MascPlug.addToolBar(QtCore.Qt.TopToolBarArea, self.dbToolBar)
        self.ToolsToolBar = QtGui.QToolBar(MascPlug)
        self.ToolsToolBar.setObjectName(_fromUtf8("ToolsToolBar"))
        MascPlug.addToolBar(QtCore.Qt.TopToolBarArea, self.ToolsToolBar)
        self.RunToolBar = QtGui.QToolBar(MascPlug)
        self.RunToolBar.setObjectName(_fromUtf8("RunToolBar"))
        MascPlug.addToolBar(QtCore.Qt.TopToolBarArea, self.RunToolBar)
        self.PostTreatmentToolBar = QtGui.QToolBar(MascPlug)
        self.PostTreatmentToolBar.setObjectName(_fromUtf8("PostTreatmentToolBar"))
        MascPlug.addToolBar(QtCore.Qt.TopToolBarArea, self.PostTreatmentToolBar)
        self.WaterQualityToolBar = QtGui.QToolBar(MascPlug)
        self.WaterQualityToolBar.setObjectName(_fromUtf8("WaterQualityToolBar"))
        MascPlug.addToolBar(QtCore.Qt.TopToolBarArea, self.WaterQualityToolBar)
        self.actionWebsite = QtGui.QAction(MascPlug)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/Mascaret/icones/webSite.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionWebsite.setIcon(icon2)
        self.actionWebsite.setObjectName(_fromUtf8("actionWebsite"))
        self.actionAbout = QtGui.QAction(MascPlug)
        self.actionAbout.setIcon(icon)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionDeleteModel = QtGui.QAction(MascPlug)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/Mascaret/icones/dbDeleteModel.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDeleteModel.setIcon(icon3)
        self.actionDeleteModel.setObjectName(_fromUtf8("actionDeleteModel"))
        self.actionRefresh_Database = QtGui.QAction(MascPlug)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/Mascaret/icones/refreshConnections.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRefresh_Database.setIcon(icon4)
        self.actionRefresh_Database.setObjectName(_fromUtf8("actionRefresh_Database"))
        self.actionExport_Model = QtGui.QAction(MascPlug)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/Mascaret/icones/dbExtractModel.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExport_Model.setIcon(icon5)
        self.actionExport_Model.setObjectName(_fromUtf8("actionExport_Model"))
        self.action_Extract_MNTfor_profile = QtGui.QAction(MascPlug)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/Mascaret/icones/mntExtract.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Extract_MNTfor_profile.setIcon(icon6)
        self.action_Extract_MNTfor_profile.setObjectName(_fromUtf8("action_Extract_MNTfor_profile"))
        self.actionSteady = QtGui.QAction(MascPlug)
        self.actionSteady.setObjectName(_fromUtf8("actionSteady"))
        self.actionUnsteady = QtGui.QAction(MascPlug)
        self.actionUnsteady.setObjectName(_fromUtf8("actionUnsteady"))
        self.actionTranscritical = QtGui.QAction(MascPlug)
        self.actionTranscritical.setObjectName(_fromUtf8("actionTranscritical"))
        self.actionCreate_Geometry = QtGui.QAction(MascPlug)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/Mascaret/icones/geo.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCreate_Geometry.setIcon(icon7)
        self.actionCreate_Geometry.setObjectName(_fromUtf8("actionCreate_Geometry"))
        self.actionCreate_xcas = QtGui.QAction(MascPlug)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/Mascaret/icones/xcas.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCreate_xcas.setIcon(icon8)
        self.actionCreate_xcas.setObjectName(_fromUtf8("actionCreate_xcas"))
        self.actionSteadyRun = QtGui.QAction(MascPlug)
        self.actionSteadyRun.setObjectName(_fromUtf8("actionSteadyRun"))
        self.actionUnsteadyRun = QtGui.QAction(MascPlug)
        self.actionUnsteadyRun.setObjectName(_fromUtf8("actionUnsteadyRun"))
        self.actionTranscriticalRun = QtGui.QAction(MascPlug)
        self.actionTranscriticalRun.setObjectName(_fromUtf8("actionTranscriticalRun"))
        self.actionObservation_Load = QtGui.QAction(MascPlug)
        self.actionObservation_Load.setObjectName(_fromUtf8("actionObservation_Load"))
        self.actionCreate_New_Model = QtGui.QAction(MascPlug)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/Mascaret/icones/dbCreateModel.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCreate_New_Model.setIcon(icon9)
        self.actionCreate_New_Model.setObjectName(_fromUtf8("actionCreate_New_Model"))
        self.actionLoad_Model = QtGui.QAction(MascPlug)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/Mascaret/icones/dbLoadModel.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLoad_Model.setIcon(icon10)
        self.actionLoad_Model.setObjectName(_fromUtf8("actionLoad_Model"))
        self.actionOptions = QtGui.QAction(MascPlug)
        self.actionOptions.setObjectName(_fromUtf8("actionOptions"))
        self.actionRestore_Default_Options = QtGui.QAction(MascPlug)
        self.actionRestore_Default_Options.setObjectName(_fromUtf8("actionRestore_Default_Options"))
        self.actionExample = QtGui.QAction(MascPlug)
        self.actionExample.setObjectName(_fromUtf8("actionExample"))
        self.actionHydrogramme = QtGui.QAction(MascPlug)
        self.actionHydrogramme.setCheckable(True)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/Mascaret/icones/hydrogramme.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionHydrogramme.setIcon(icon11)
        self.actionHydrogramme.setObjectName(_fromUtf8("actionHydrogramme"))
        self.actionCross_section = QtGui.QAction(MascPlug)
        self.actionCross_section.setCheckable(True)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/Mascaret/icones/profil.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCross_section.setIcon(icon12)
        self.actionCross_section.setObjectName(_fromUtf8("actionCross_section"))
        self.actionCross_section_results = QtGui.QAction(MascPlug)
        self.actionCross_section_results.setCheckable(True)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/Mascaret/icones/profilResult.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCross_section_results.setIcon(icon13)
        self.actionCross_section_results.setObjectName(_fromUtf8("actionCross_section_results"))
        self.actionParameters = QtGui.QAction(MascPlug)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/Mascaret/icones/parameter.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionParameters.setIcon(icon14)
        self.actionParameters.setObjectName(_fromUtf8("actionParameters"))
        self.actionRun = QtGui.QAction(MascPlug)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/Mascaret/icones/play.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRun.setIcon(icon15)
        self.actionRun.setObjectName(_fromUtf8("actionRun"))
        self.actionDelete_Run = QtGui.QAction(MascPlug)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/Mascaret/icones/croix.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDelete_Run.setIcon(icon16)
        self.actionDelete_Run.setObjectName(_fromUtf8("actionDelete_Run"))
        self.actionExport_Run = QtGui.QAction(MascPlug)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/Mascaret/icones/repSav.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExport_Run.setIcon(icon17)
        self.actionExport_Run.setObjectName(_fromUtf8("actionExport_Run"))
        self.actionImport_Model = QtGui.QAction(MascPlug)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/Mascaret/icones/dbImportModel.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionImport_Model.setIcon(icon18)
        self.actionImport_Model.setObjectName(_fromUtf8("actionImport_Model"))
        self.actionParameters_Water_Quality = QtGui.QAction(MascPlug)
        self.actionParameters_Water_Quality.setEnabled(True)
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/Mascaret/icones/parameterWQ.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionParameters_Water_Quality.setIcon(icon19)
        self.actionParameters_Water_Quality.setObjectName(_fromUtf8("actionParameters_Water_Quality"))
        self.actionTracer_Laws = QtGui.QAction(MascPlug)
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/Mascaret/icones/lawWQ.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionTracer_Laws.setIcon(icon20)
        self.actionTracer_Laws.setObjectName(_fromUtf8("actionTracer_Laws"))
        self.menuSetting.addAction(self.actionOptions)
        self.menuSetting.addAction(self.actionRestore_Default_Options)
        self.menuHelp.addAction(self.menuSetting.menuAction())
        self.menuHelp.addAction(self.actionWebsite)
        self.menuHelp.addAction(self.actionAbout)
        self.menu_Tools.addAction(self.actionCross_section)
        self.menu_Tools.addAction(self.action_Extract_MNTfor_profile)
        self.menuDB.addAction(self.actionRefresh_Database)
        self.menuDB.addSeparator()
        self.menuDB.addAction(self.actionCreate_New_Model)
        self.menuDB.addAction(self.actionLoad_Model)
        self.menuDB.addAction(self.actionDeleteModel)
        self.menuDB.addSeparator()
        self.menuDB.addAction(self.actionExport_Model)
        self.menuDB.addAction(self.actionImport_Model)
        self.menuRun.addAction(self.actionParameters)
        self.menuRun.addSeparator()
        self.menuRun.addAction(self.actionCreate_Geometry)
        self.menuRun.addAction(self.actionCreate_xcas)
        self.menuRun.addSeparator()
        self.menuRun.addAction(self.actionRun)
        self.menuRun.addSeparator()
        self.menuRun.addAction(self.actionExport_Run)
        self.menuRun.addAction(self.actionDelete_Run)
        self.menuPost_Treatment.addAction(self.actionHydrogramme)
        self.menuPost_Treatment.addAction(self.actionCross_section_results)
        self.menuWater_Quality.addAction(self.actionParameters_Water_Quality)
        self.menuWater_Quality.addAction(self.actionTracer_Laws)
        self.menubar.addAction(self.menuDB.menuAction())
        self.menubar.addAction(self.menu_Tools.menuAction())
        self.menubar.addAction(self.menuRun.menuAction())
        self.menubar.addAction(self.menuPost_Treatment.menuAction())
        self.menubar.addAction(self.menuWater_Quality.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.dbToolBar.addAction(self.actionRefresh_Database)
        self.dbToolBar.addAction(self.actionCreate_New_Model)
        self.dbToolBar.addAction(self.actionLoad_Model)
        self.dbToolBar.addAction(self.actionDeleteModel)
        self.dbToolBar.addAction(self.actionExport_Model)
        self.dbToolBar.addAction(self.actionImport_Model)
        self.ToolsToolBar.addAction(self.actionCross_section)
        self.ToolsToolBar.addAction(self.action_Extract_MNTfor_profile)
        self.ToolsToolBar.addSeparator()
        self.RunToolBar.addAction(self.actionParameters)
        self.RunToolBar.addSeparator()
        self.RunToolBar.addAction(self.actionCreate_Geometry)
        self.RunToolBar.addAction(self.actionCreate_xcas)
        self.RunToolBar.addSeparator()
        self.RunToolBar.addAction(self.actionRun)
        self.RunToolBar.addSeparator()
        self.RunToolBar.addAction(self.actionExport_Run)
        self.RunToolBar.addAction(self.actionDelete_Run)
        self.PostTreatmentToolBar.addAction(self.actionHydrogramme)
        self.PostTreatmentToolBar.addAction(self.actionCross_section_results)
        self.WaterQualityToolBar.addAction(self.actionParameters_Water_Quality)
        self.WaterQualityToolBar.addAction(self.actionTracer_Laws)

        self.retranslateUi(MascPlug)
        QtCore.QMetaObject.connectSlotsByName(MascPlug)

    def retranslateUi(self, MascPlug):
        MascPlug.setWindowTitle(_translate("MascPlug", "Mascaret", None))
        self.label.setText(_translate("MascPlug", "Projection", None))
        self.labelCurDatabase.setText(_translate("MascPlug", "DB Connection:", None))
        self.menuHelp.setTitle(_translate("MascPlug", "Help", None))
        self.menuSetting.setTitle(_translate("MascPlug", "Setting", None))
        self.menu_Tools.setTitle(_translate("MascPlug", "Tools", None))
        self.menuDB.setTitle(_translate("MascPlug", "Database", None))
        self.menuRun.setTitle(_translate("MascPlug", "Run", None))
        self.menuPost_Treatment.setTitle(_translate("MascPlug", "Post-Treatment", None))
        self.menuWater_Quality.setTitle(_translate("MascPlug", "Water Quality", None))
        self.dbToolBar.setWindowTitle(_translate("MascPlug", "toolBar", None))
        self.ToolsToolBar.setWindowTitle(_translate("MascPlug", "toolBar", None))
        self.RunToolBar.setWindowTitle(_translate("MascPlug", "toolBar", None))
        self.PostTreatmentToolBar.setWindowTitle(_translate("MascPlug", "toolBar", None))
        self.WaterQualityToolBar.setWindowTitle(_translate("MascPlug", "toolBar", None))
        self.actionWebsite.setText(_translate("MascPlug", "Web site", None))
        self.actionAbout.setText(_translate("MascPlug", "About", None))
        self.actionDeleteModel.setText(_translate("MascPlug", "Delete Model", None))
        self.actionRefresh_Database.setText(_translate("MascPlug", "Refresh Connections List", None))
        self.actionExport_Model.setText(_translate("MascPlug", "Export Model", None))
        self.action_Extract_MNTfor_profile.setText(_translate("MascPlug", " Extract MNT for profile", None))
        self.actionSteady.setText(_translate("MascPlug", "Steady", None))
        self.actionUnsteady.setText(_translate("MascPlug", "Unsteady", None))
        self.actionTranscritical.setText(_translate("MascPlug", "Transcritical", None))
        self.actionCreate_Geometry.setText(_translate("MascPlug", "Create Geometry", None))
        self.actionCreate_xcas.setText(_translate("MascPlug", "Create xcas", None))
        self.actionSteadyRun.setText(_translate("MascPlug", "Steady", None))
        self.actionUnsteadyRun.setText(_translate("MascPlug", "Unsteady", None))
        self.actionTranscriticalRun.setText(_translate("MascPlug", "Transcritical", None))
        self.actionObservation_Load.setText(_translate("MascPlug", "Observation Load", None))
        self.actionCreate_New_Model.setText(_translate("MascPlug", "Create New Model", None))
        self.actionLoad_Model.setText(_translate("MascPlug", "Load Model", None))
        self.actionOptions.setText(_translate("MascPlug", "Options", None))
        self.actionRestore_Default_Options.setText(_translate("MascPlug", "Restore Default Options", None))
        self.actionExample.setText(_translate("MascPlug", "Create example", None))
        self.actionHydrogramme.setText(_translate("MascPlug", "Hydrogramme", None))
        self.actionCross_section.setText(_translate("MascPlug", "Cross section", None))
        self.actionCross_section_results.setText(_translate("MascPlug", "Cross section results", None))
        self.actionParameters.setText(_translate("MascPlug", "Parameters", None))
        self.actionRun.setText(_translate("MascPlug", "Run", None))
        self.actionDelete_Run.setText(_translate("MascPlug", "Delete Run", None))
        self.actionExport_Run.setText(_translate("MascPlug", "Export last run case", None))
        self.actionImport_Model.setText(_translate("MascPlug", "Import Model", None))
        self.actionParameters_Water_Quality.setText(_translate("MascPlug", "Parameters WQ", None))
        self.actionTracer_Laws.setText(_translate("MascPlug", "Tracer Laws", None))

from qgis.gui import QgsProjectionSelectionWidget

