# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_parameter.ui'
#
# Created: Wed Sep 27 10:02:42 2017
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Parameters(object):
    def setupUi(self, Parameters):
        Parameters.setObjectName(_fromUtf8("Parameters"))
        Parameters.resize(699, 549)
        Parameters.setSizeGripEnabled(False)
        Parameters.setModal(True)
        self.gridLayout = QtGui.QGridLayout(Parameters)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.tabWidget = QtGui.QTabWidget(Parameters)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabConfig = QtGui.QWidget()
        self.tabConfig.setObjectName(_fromUtf8("tabConfig"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tabConfig)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.b_delete_law = QtGui.QPushButton(self.tabConfig)
        self.b_delete_law.setEnabled(False)
        self.b_delete_law.setObjectName(_fromUtf8("b_delete_law"))
        self.gridLayout_3.addWidget(self.b_delete_law, 3, 2, 1, 1)
        self.b_load_law = QtGui.QPushButton(self.tabConfig)
        self.b_load_law.setEnabled(False)
        self.b_load_law.setObjectName(_fromUtf8("b_load_law"))
        self.gridLayout_3.addWidget(self.b_load_law, 3, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 0, 0, 1, 1)
        self.label = QtGui.QLabel(self.tabConfig)
        self.label.setEnabled(False)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_3.addWidget(self.label, 3, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem1, 4, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem2, 2, 0, 1, 1)
        self.evenement = QtGui.QRadioButton(self.tabConfig)
        self.evenement.setObjectName(_fromUtf8("evenement"))
        self.gridLayout_3.addWidget(self.evenement, 1, 2, 1, 1)
        self.radioButton_law = QtGui.QRadioButton(self.tabConfig)
        self.radioButton_law.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.radioButton_law.setChecked(True)
        self.radioButton_law.setObjectName(_fromUtf8("radioButton_law"))
        self.gridLayout_3.addWidget(self.radioButton_law, 1, 0, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem3, 3, 3, 1, 1)
        self.tabWidget.addTab(self.tabConfig, _fromUtf8(""))
        self.tabPhyMod = QtGui.QWidget()
        self.tabPhyMod.setObjectName(_fromUtf8("tabPhyMod"))
        self.gridLayout_4 = QtGui.QGridLayout(self.tabPhyMod)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.perteChargeConf = QtGui.QCheckBox(self.tabPhyMod)
        self.perteChargeConf.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.perteChargeConf.setObjectName(_fromUtf8("perteChargeConf"))
        self.gridLayout_2.addWidget(self.perteChargeConf, 0, 0, 1, 1)
        self.interpolLinStrickler = QtGui.QCheckBox(self.tabPhyMod)
        self.interpolLinStrickler.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.interpolLinStrickler.setObjectName(_fromUtf8("interpolLinStrickler"))
        self.gridLayout_2.addWidget(self.interpolLinStrickler, 6, 0, 1, 1)
        self.label_elevCoteArrivFront = QtGui.QLabel(self.tabPhyMod)
        self.label_elevCoteArrivFront.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_elevCoteArrivFront.setTextFormat(QtCore.Qt.AutoText)
        self.label_elevCoteArrivFront.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_elevCoteArrivFront.setObjectName(_fromUtf8("label_elevCoteArrivFront"))
        self.gridLayout_2.addWidget(self.label_elevCoteArrivFront, 4, 0, 1, 1)
        self.label_compositionLits = QtGui.QLabel(self.tabPhyMod)
        self.label_compositionLits.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_compositionLits.setObjectName(_fromUtf8("label_compositionLits"))
        self.gridLayout_2.addWidget(self.label_compositionLits, 2, 0, 1, 1)
        self.compositionLits = QtGui.QComboBox(self.tabPhyMod)
        self.compositionLits.setObjectName(_fromUtf8("compositionLits"))
        self.compositionLits.addItem(_fromUtf8(""))
        self.compositionLits.addItem(_fromUtf8(""))
        self.compositionLits.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.compositionLits, 2, 1, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem4, 9, 0, 1, 1)
        self.litMajeur = QtGui.QCheckBox(self.tabPhyMod)
        self.litMajeur.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.litMajeur.setObjectName(_fromUtf8("litMajeur"))
        self.gridLayout_2.addWidget(self.litMajeur, 7, 0, 1, 1)
        self.zoneStock = QtGui.QCheckBox(self.tabPhyMod)
        self.zoneStock.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.zoneStock.setObjectName(_fromUtf8("zoneStock"))
        self.gridLayout_2.addWidget(self.zoneStock, 8, 0, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem5, 0, 1, 1, 1)
        self.conservFrotVertical = QtGui.QCheckBox(self.tabPhyMod)
        self.conservFrotVertical.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.conservFrotVertical.setObjectName(_fromUtf8("conservFrotVertical"))
        self.gridLayout_2.addWidget(self.conservFrotVertical, 5, 0, 1, 1)
        self.elevCoteArrivFront = QtGui.QDoubleSpinBox(self.tabPhyMod)
        self.elevCoteArrivFront.setMaximum(1000000000.0)
        self.elevCoteArrivFront.setSingleStep(0.01)
        self.elevCoteArrivFront.setProperty("value", 0.05)
        self.elevCoteArrivFront.setObjectName(_fromUtf8("elevCoteArrivFront"))
        self.gridLayout_2.addWidget(self.elevCoteArrivFront, 4, 1, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem6, 4, 2, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabPhyMod, _fromUtf8(""))
        self.tabNum = QtGui.QWidget()
        self.tabNum.setObjectName(_fromUtf8("tabNum"))
        self.gridLayout_6 = QtGui.QGridLayout(self.tabNum)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem7, 0, 1, 1, 1)
        self.froudeLimCondLim = QtGui.QDoubleSpinBox(self.tabNum)
        self.froudeLimCondLim.setDecimals(1)
        self.froudeLimCondLim.setMaximum(1000000000.0)
        self.froudeLimCondLim.setSingleStep(0.1)
        self.froudeLimCondLim.setProperty("value", 1.0)
        self.froudeLimCondLim.setObjectName(_fromUtf8("froudeLimCondLim"))
        self.gridLayout_5.addWidget(self.froudeLimCondLim, 2, 1, 1, 1)
        self.optimisNoyauTrans = QtGui.QCheckBox(self.tabNum)
        self.optimisNoyauTrans.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.optimisNoyauTrans.setObjectName(_fromUtf8("optimisNoyauTrans"))
        self.gridLayout_5.addWidget(self.optimisNoyauTrans, 5, 0, 1, 1)
        self.perteChargeAutoElargissement = QtGui.QCheckBox(self.tabNum)
        self.perteChargeAutoElargissement.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.perteChargeAutoElargissement.setObjectName(_fromUtf8("perteChargeAutoElargissement"))
        self.gridLayout_5.addWidget(self.perteChargeAutoElargissement, 6, 0, 1, 1)
        self.implicitNoyauTrans = QtGui.QCheckBox(self.tabNum)
        self.implicitNoyauTrans.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.implicitNoyauTrans.setObjectName(_fromUtf8("implicitNoyauTrans"))
        self.gridLayout_5.addWidget(self.implicitNoyauTrans, 4, 0, 1, 1)
        self.calcOndeSubmersion = QtGui.QCheckBox(self.tabNum)
        self.calcOndeSubmersion.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.calcOndeSubmersion.setObjectName(_fromUtf8("calcOndeSubmersion"))
        self.gridLayout_5.addWidget(self.calcOndeSubmersion, 1, 0, 1, 1)
        self.termesNonHydrostatiques = QtGui.QCheckBox(self.tabNum)
        self.termesNonHydrostatiques.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.termesNonHydrostatiques.setObjectName(_fromUtf8("termesNonHydrostatiques"))
        self.gridLayout_5.addWidget(self.termesNonHydrostatiques, 7, 0, 1, 1)
        self.attenuationConvection = QtGui.QCheckBox(self.tabNum)
        self.attenuationConvection.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.attenuationConvection.setObjectName(_fromUtf8("attenuationConvection"))
        self.gridLayout_5.addWidget(self.attenuationConvection, 0, 0, 1, 1)
        self.pasTempsVar = QtGui.QCheckBox(self.tabNum)
        self.pasTempsVar.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.pasTempsVar.setObjectName(_fromUtf8("pasTempsVar"))
        self.gridLayout_5.addWidget(self.pasTempsVar, 8, 0, 1, 1)
        self.label_froudeLimCondLim = QtGui.QLabel(self.tabNum)
        self.label_froudeLimCondLim.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_froudeLimCondLim.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_froudeLimCondLim.setObjectName(_fromUtf8("label_froudeLimCondLim"))
        self.gridLayout_5.addWidget(self.label_froudeLimCondLim, 2, 0, 1, 1)
        self.traitImplicitFrot = QtGui.QCheckBox(self.tabNum)
        self.traitImplicitFrot.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.traitImplicitFrot.setObjectName(_fromUtf8("traitImplicitFrot"))
        self.gridLayout_5.addWidget(self.traitImplicitFrot, 3, 0, 1, 1)
        spacerItem8 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem8, 9, 0, 1, 1)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem9, 2, 2, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_5, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabNum, _fromUtf8(""))
        self.tabTemp = QtGui.QWidget()
        self.tabTemp.setObjectName(_fromUtf8("tabTemp"))
        self.gridLayout_8 = QtGui.QGridLayout(self.tabTemp)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.gridLayout_7 = QtGui.QGridLayout()
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.nbPasTemps = QtGui.QSpinBox(self.tabTemp)
        self.nbPasTemps.setMinimum(0)
        self.nbPasTemps.setMaximum(999999999)
        self.nbPasTemps.setObjectName(_fromUtf8("nbPasTemps"))
        self.gridLayout_7.addWidget(self.nbPasTemps, 3, 1, 1, 1)
        self.label_tempsInit = QtGui.QLabel(self.tabTemp)
        self.label_tempsInit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_tempsInit.setObjectName(_fromUtf8("label_tempsInit"))
        self.gridLayout_7.addWidget(self.label_tempsInit, 2, 0, 1, 1)
        self.tempsInit = QtGui.QDoubleSpinBox(self.tabTemp)
        self.tempsInit.setDecimals(1)
        self.tempsInit.setMaximum(1000000000.0)
        self.tempsInit.setSingleStep(0.1)
        self.tempsInit.setObjectName(_fromUtf8("tempsInit"))
        self.gridLayout_7.addWidget(self.tempsInit, 2, 1, 1, 1)
        self.label_tempsMax = QtGui.QLabel(self.tabTemp)
        self.label_tempsMax.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_tempsMax.setObjectName(_fromUtf8("label_tempsMax"))
        self.gridLayout_7.addWidget(self.label_tempsMax, 4, 0, 1, 1)
        self.label_coteMax = QtGui.QLabel(self.tabTemp)
        self.label_coteMax.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_coteMax.setObjectName(_fromUtf8("label_coteMax"))
        self.gridLayout_7.addWidget(self.label_coteMax, 6, 0, 1, 1)
        self.critereArret = QtGui.QComboBox(self.tabTemp)
        self.critereArret.setObjectName(_fromUtf8("critereArret"))
        self.critereArret.addItem(_fromUtf8(""))
        self.critereArret.addItem(_fromUtf8(""))
        self.critereArret.addItem(_fromUtf8(""))
        self.gridLayout_7.addWidget(self.critereArret, 0, 1, 1, 1)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem10, 9, 1, 1, 1)
        self.label_abscisseControle = QtGui.QLabel(self.tabTemp)
        self.label_abscisseControle.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_abscisseControle.setObjectName(_fromUtf8("label_abscisseControle"))
        self.gridLayout_7.addWidget(self.label_abscisseControle, 7, 0, 1, 1)
        spacerItem11 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem11, 9, 0, 1, 1)
        self.label_nbPasTemps = QtGui.QLabel(self.tabTemp)
        self.label_nbPasTemps.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_nbPasTemps.setObjectName(_fromUtf8("label_nbPasTemps"))
        self.gridLayout_7.addWidget(self.label_nbPasTemps, 3, 0, 1, 1)
        self.label_nbCourant = QtGui.QLabel(self.tabTemp)
        self.label_nbCourant.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_nbCourant.setObjectName(_fromUtf8("label_nbCourant"))
        self.gridLayout_7.addWidget(self.label_nbCourant, 5, 0, 1, 1)
        self.label_pasTemps = QtGui.QLabel(self.tabTemp)
        self.label_pasTemps.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_pasTemps.setObjectName(_fromUtf8("label_pasTemps"))
        self.gridLayout_7.addWidget(self.label_pasTemps, 1, 0, 1, 1)
        self.label_critereArret = QtGui.QLabel(self.tabTemp)
        self.label_critereArret.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_critereArret.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_critereArret.setObjectName(_fromUtf8("label_critereArret"))
        self.gridLayout_7.addWidget(self.label_critereArret, 0, 0, 1, 1)
        self.pasTemps = QtGui.QDoubleSpinBox(self.tabTemp)
        self.pasTemps.setDecimals(1)
        self.pasTemps.setMaximum(1000000000.0)
        self.pasTemps.setSingleStep(0.1)
        self.pasTemps.setProperty("value", 1.0)
        self.pasTemps.setObjectName(_fromUtf8("pasTemps"))
        self.gridLayout_7.addWidget(self.pasTemps, 1, 1, 1, 1)
        self.coteMax = QtGui.QDoubleSpinBox(self.tabTemp)
        self.coteMax.setDecimals(2)
        self.coteMax.setMaximum(1000000000.0)
        self.coteMax.setSingleStep(0.01)
        self.coteMax.setProperty("value", 0.0)
        self.coteMax.setObjectName(_fromUtf8("coteMax"))
        self.gridLayout_7.addWidget(self.coteMax, 6, 1, 1, 1)
        self.nbCourant = QtGui.QDoubleSpinBox(self.tabTemp)
        self.nbCourant.setMaximum(99.99)
        self.nbCourant.setSingleStep(0.01)
        self.nbCourant.setProperty("value", 0.8)
        self.nbCourant.setObjectName(_fromUtf8("nbCourant"))
        self.gridLayout_7.addWidget(self.nbCourant, 5, 1, 1, 1)
        self.tempsMax = QtGui.QDoubleSpinBox(self.tabTemp)
        self.tempsMax.setMaximum(1000000000.0)
        self.tempsMax.setProperty("value", 100.0)
        self.tempsMax.setObjectName(_fromUtf8("tempsMax"))
        self.gridLayout_7.addWidget(self.tempsMax, 4, 1, 1, 1)
        self.label_biefControle = QtGui.QLabel(self.tabTemp)
        self.label_biefControle.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_biefControle.setObjectName(_fromUtf8("label_biefControle"))
        self.gridLayout_7.addWidget(self.label_biefControle, 8, 0, 1, 1)
        self.biefControle = QtGui.QSpinBox(self.tabTemp)
        self.biefControle.setMaximum(999999999)
        self.biefControle.setObjectName(_fromUtf8("biefControle"))
        self.gridLayout_7.addWidget(self.biefControle, 8, 1, 1, 1)
        self.abscisseControle = QtGui.QDoubleSpinBox(self.tabTemp)
        self.abscisseControle.setDecimals(1)
        self.abscisseControle.setMaximum(1000000000.0)
        self.abscisseControle.setSingleStep(0.1)
        self.abscisseControle.setObjectName(_fromUtf8("abscisseControle"))
        self.gridLayout_7.addWidget(self.abscisseControle, 7, 1, 1, 1)
        spacerItem12 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem12, 8, 2, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_7, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabTemp, _fromUtf8(""))
        self.tabInitBound = QtGui.QWidget()
        self.tabInitBound.setObjectName(_fromUtf8("tabInitBound"))
        self.gridLayout_10 = QtGui.QGridLayout(self.tabInitBound)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.gridLayout_9 = QtGui.QGridLayout()
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.initialisationAuto = QtGui.QCheckBox(self.tabInitBound)
        self.initialisationAuto.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.initialisationAuto.setObjectName(_fromUtf8("initialisationAuto"))
        self.gridLayout_9.addWidget(self.initialisationAuto, 0, 0, 1, 1)
        spacerItem13 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_9.addItem(spacerItem13, 3, 0, 1, 1)
        self.LigEauInit = QtGui.QCheckBox(self.tabInitBound)
        self.LigEauInit.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.LigEauInit.setObjectName(_fromUtf8("LigEauInit"))
        self.gridLayout_9.addWidget(self.LigEauInit, 1, 0, 1, 1)
        self.repriseCalcul = QtGui.QCheckBox(self.tabInitBound)
        self.repriseCalcul.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.repriseCalcul.setObjectName(_fromUtf8("repriseCalcul"))
        self.gridLayout_9.addWidget(self.repriseCalcul, 2, 0, 1, 1)
        spacerItem14 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem14, 1, 2, 1, 1)
        spacerItem15 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem15, 1, 1, 1, 1)
        self.gridLayout_10.addLayout(self.gridLayout_9, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabInitBound, _fromUtf8(""))
        self.tabRes = QtGui.QWidget()
        self.tabRes.setObjectName(_fromUtf8("tabRes"))
        self.gridLayout_12 = QtGui.QGridLayout(self.tabRes)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.gridLayout_11 = QtGui.QGridLayout()
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.label_pasStock = QtGui.QLabel(self.tabRes)
        self.label_pasStock.setObjectName(_fromUtf8("label_pasStock"))
        self.gridLayout_11.addWidget(self.label_pasStock, 7, 0, 1, 1)
        self.impressionligneEauInitiale = QtGui.QCheckBox(self.tabRes)
        self.impressionligneEauInitiale.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.impressionligneEauInitiale.setObjectName(_fromUtf8("impressionligneEauInitiale"))
        self.gridLayout_11.addWidget(self.impressionligneEauInitiale, 4, 0, 1, 1)
        self.impressionCalcul = QtGui.QCheckBox(self.tabRes)
        self.impressionCalcul.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.impressionCalcul.setObjectName(_fromUtf8("impressionCalcul"))
        self.gridLayout_11.addWidget(self.impressionCalcul, 5, 0, 1, 1)
        self.impressionPlanimetrage = QtGui.QCheckBox(self.tabRes)
        self.impressionPlanimetrage.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.impressionPlanimetrage.setObjectName(_fromUtf8("impressionPlanimetrage"))
        self.gridLayout_11.addWidget(self.impressionPlanimetrage, 1, 0, 1, 1)
        spacerItem16 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_11.addItem(spacerItem16, 11, 0, 1, 1)
        self.impressionReseau = QtGui.QCheckBox(self.tabRes)
        self.impressionReseau.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.impressionReseau.setObjectName(_fromUtf8("impressionReseau"))
        self.gridLayout_11.addWidget(self.impressionReseau, 2, 0, 1, 1)
        self.label_pasImpression = QtGui.QLabel(self.tabRes)
        self.label_pasImpression.setObjectName(_fromUtf8("label_pasImpression"))
        self.gridLayout_11.addWidget(self.label_pasImpression, 8, 0, 1, 1)
        self.impressionGeometrie = QtGui.QCheckBox(self.tabRes)
        self.impressionGeometrie.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.impressionGeometrie.setObjectName(_fromUtf8("impressionGeometrie"))
        self.gridLayout_11.addWidget(self.impressionGeometrie, 0, 0, 1, 1)
        self.label_ecartInterBranch = QtGui.QLabel(self.tabRes)
        self.label_ecartInterBranch.setObjectName(_fromUtf8("label_ecartInterBranch"))
        self.gridLayout_11.addWidget(self.label_ecartInterBranch, 9, 0, 1, 1)
        self.label_premPasTpsStock = QtGui.QLabel(self.tabRes)
        self.label_premPasTpsStock.setObjectName(_fromUtf8("label_premPasTpsStock"))
        self.gridLayout_11.addWidget(self.label_premPasTpsStock, 6, 0, 1, 1)
        self.impressionLoiHydraulique = QtGui.QCheckBox(self.tabRes)
        self.impressionLoiHydraulique.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.impressionLoiHydraulique.setObjectName(_fromUtf8("impressionLoiHydraulique"))
        self.gridLayout_11.addWidget(self.impressionLoiHydraulique, 3, 0, 1, 1)
        self.label_option = QtGui.QLabel(self.tabRes)
        self.label_option.setObjectName(_fromUtf8("label_option"))
        self.gridLayout_11.addWidget(self.label_option, 10, 0, 1, 1)
        self.option = QtGui.QComboBox(self.tabRes)
        self.option.setObjectName(_fromUtf8("option"))
        self.option.addItem(_fromUtf8(""))
        self.option.addItem(_fromUtf8(""))
        self.gridLayout_11.addWidget(self.option, 10, 1, 1, 1)
        self.ecartInterBranch = QtGui.QDoubleSpinBox(self.tabRes)
        self.ecartInterBranch.setDecimals(1)
        self.ecartInterBranch.setMaximum(1000000000.0)
        self.ecartInterBranch.setSingleStep(0.1)
        self.ecartInterBranch.setObjectName(_fromUtf8("ecartInterBranch"))
        self.gridLayout_11.addWidget(self.ecartInterBranch, 9, 1, 1, 1)
        self.pasImpression = QtGui.QSpinBox(self.tabRes)
        self.pasImpression.setMaximum(999999999)
        self.pasImpression.setObjectName(_fromUtf8("pasImpression"))
        self.gridLayout_11.addWidget(self.pasImpression, 8, 1, 1, 1)
        self.pasStock = QtGui.QSpinBox(self.tabRes)
        self.pasStock.setMaximum(999999999)
        self.pasStock.setObjectName(_fromUtf8("pasStock"))
        self.gridLayout_11.addWidget(self.pasStock, 7, 1, 1, 1)
        self.premPasTpsStock = QtGui.QSpinBox(self.tabRes)
        self.premPasTpsStock.setMaximum(999999999)
        self.premPasTpsStock.setObjectName(_fromUtf8("premPasTpsStock"))
        self.gridLayout_11.addWidget(self.premPasTpsStock, 6, 1, 1, 1)
        spacerItem17 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem17, 7, 2, 1, 1)
        self.gridLayout_12.addLayout(self.gridLayout_11, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabRes, _fromUtf8(""))
        self.tabOut = QtGui.QWidget()
        self.tabOut.setObjectName(_fromUtf8("tabOut"))
        self.gridLayout_14 = QtGui.QGridLayout(self.tabOut)
        self.gridLayout_14.setObjectName(_fromUtf8("gridLayout_14"))
        self.gridLayout_13 = QtGui.QGridLayout()
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        self.box_hydro = QtGui.QGroupBox(self.tabOut)
        self.box_hydro.setCheckable(True)
        self.box_hydro.setChecked(True)
        self.box_hydro.setObjectName(_fromUtf8("box_hydro"))
        self.gridLayout_17 = QtGui.QGridLayout(self.box_hydro)
        self.gridLayout_17.setObjectName(_fromUtf8("gridLayout_17"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.S1 = QtGui.QCheckBox(self.box_hydro)
        self.S1.setObjectName(_fromUtf8("S1"))
        self.verticalLayout_3.addWidget(self.S1)
        self.S2 = QtGui.QCheckBox(self.box_hydro)
        self.S2.setObjectName(_fromUtf8("S2"))
        self.verticalLayout_3.addWidget(self.S2)
        self.B1 = QtGui.QCheckBox(self.box_hydro)
        self.B1.setObjectName(_fromUtf8("B1"))
        self.verticalLayout_3.addWidget(self.B1)
        self.B2 = QtGui.QCheckBox(self.box_hydro)
        self.B2.setObjectName(_fromUtf8("B2"))
        self.verticalLayout_3.addWidget(self.B2)
        self.BS = QtGui.QCheckBox(self.box_hydro)
        self.BS.setObjectName(_fromUtf8("BS"))
        self.verticalLayout_3.addWidget(self.BS)
        self.P1 = QtGui.QCheckBox(self.box_hydro)
        self.P1.setObjectName(_fromUtf8("P1"))
        self.verticalLayout_3.addWidget(self.P1)
        self.P2 = QtGui.QCheckBox(self.box_hydro)
        self.P2.setObjectName(_fromUtf8("P2"))
        self.verticalLayout_3.addWidget(self.P2)
        self.RH1 = QtGui.QCheckBox(self.box_hydro)
        self.RH1.setObjectName(_fromUtf8("RH1"))
        self.verticalLayout_3.addWidget(self.RH1)
        self.RH2 = QtGui.QCheckBox(self.box_hydro)
        self.RH2.setObjectName(_fromUtf8("RH2"))
        self.verticalLayout_3.addWidget(self.RH2)
        self.SS = QtGui.QCheckBox(self.box_hydro)
        self.SS.setObjectName(_fromUtf8("SS"))
        self.verticalLayout_3.addWidget(self.SS)
        self.VOL = QtGui.QCheckBox(self.box_hydro)
        self.VOL.setObjectName(_fromUtf8("VOL"))
        self.verticalLayout_3.addWidget(self.VOL)
        self.VOLS = QtGui.QCheckBox(self.box_hydro)
        self.VOLS.setObjectName(_fromUtf8("VOLS"))
        self.verticalLayout_3.addWidget(self.VOLS)
        self.BMAX = QtGui.QCheckBox(self.box_hydro)
        self.BMAX.setObjectName(_fromUtf8("BMAX"))
        self.verticalLayout_3.addWidget(self.BMAX)
        spacerItem18 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem18)
        self.gridLayout_17.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.gridLayout_13.addWidget(self.box_hydro, 0, 2, 1, 1)
        self.box_WaterLevel = QtGui.QGroupBox(self.tabOut)
        self.box_WaterLevel.setEnabled(True)
        self.box_WaterLevel.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.box_WaterLevel.setAcceptDrops(False)
        self.box_WaterLevel.setAutoFillBackground(False)
        self.box_WaterLevel.setCheckable(True)
        self.box_WaterLevel.setChecked(True)
        self.box_WaterLevel.setObjectName(_fromUtf8("box_WaterLevel"))
        self.gridLayout_15 = QtGui.QGridLayout(self.box_WaterLevel)
        self.gridLayout_15.setObjectName(_fromUtf8("gridLayout_15"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.ZREF = QtGui.QCheckBox(self.box_WaterLevel)
        self.ZREF.setObjectName(_fromUtf8("ZREF"))
        self.verticalLayout.addWidget(self.ZREF)
        self.RGC = QtGui.QCheckBox(self.box_WaterLevel)
        self.RGC.setObjectName(_fromUtf8("RGC"))
        self.verticalLayout.addWidget(self.RGC)
        self.RDC = QtGui.QCheckBox(self.box_WaterLevel)
        self.RDC.setObjectName(_fromUtf8("RDC"))
        self.verticalLayout.addWidget(self.RDC)
        self.Z = QtGui.QCheckBox(self.box_WaterLevel)
        self.Z.setObjectName(_fromUtf8("Z"))
        self.verticalLayout.addWidget(self.Z)
        self.Y = QtGui.QCheckBox(self.box_WaterLevel)
        self.Y.setObjectName(_fromUtf8("Y"))
        self.verticalLayout.addWidget(self.Y)
        self.HMOY = QtGui.QCheckBox(self.box_WaterLevel)
        self.HMOY.setObjectName(_fromUtf8("HMOY"))
        self.verticalLayout.addWidget(self.HMOY)
        self.ZMAX = QtGui.QCheckBox(self.box_WaterLevel)
        self.ZMAX.setObjectName(_fromUtf8("ZMAX"))
        self.verticalLayout.addWidget(self.ZMAX)
        self.ZMIN = QtGui.QCheckBox(self.box_WaterLevel)
        self.ZMIN.setObjectName(_fromUtf8("ZMIN"))
        self.verticalLayout.addWidget(self.ZMIN)
        spacerItem19 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem19)
        self.gridLayout_15.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.gridLayout_13.addWidget(self.box_WaterLevel, 0, 0, 1, 1)
        self.box_time = QtGui.QGroupBox(self.tabOut)
        self.box_time.setCheckable(True)
        self.box_time.setChecked(True)
        self.box_time.setObjectName(_fromUtf8("box_time"))
        self.gridLayout_18 = QtGui.QGridLayout(self.box_time)
        self.gridLayout_18.setObjectName(_fromUtf8("gridLayout_18"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.TZMA = QtGui.QCheckBox(self.box_time)
        self.TZMA.setObjectName(_fromUtf8("TZMA"))
        self.verticalLayout_4.addWidget(self.TZMA)
        self.TZMI = QtGui.QCheckBox(self.box_time)
        self.TZMI.setObjectName(_fromUtf8("TZMI"))
        self.verticalLayout_4.addWidget(self.TZMI)
        self.TOND = QtGui.QCheckBox(self.box_time)
        self.TOND.setObjectName(_fromUtf8("TOND"))
        self.verticalLayout_4.addWidget(self.TOND)
        self.TQMA = QtGui.QCheckBox(self.box_time)
        self.TQMA.setObjectName(_fromUtf8("TQMA"))
        self.verticalLayout_4.addWidget(self.TQMA)
        spacerItem20 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem20)
        self.gridLayout_18.addLayout(self.verticalLayout_4, 0, 0, 1, 1)
        self.gridLayout_13.addWidget(self.box_time, 1, 0, 1, 1)
        self.box_velocity = QtGui.QGroupBox(self.tabOut)
        self.box_velocity.setCheckable(True)
        self.box_velocity.setChecked(True)
        self.box_velocity.setObjectName(_fromUtf8("box_velocity"))
        self.gridLayout_16 = QtGui.QGridLayout(self.box_velocity)
        self.gridLayout_16.setObjectName(_fromUtf8("gridLayout_16"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.QMIN = QtGui.QCheckBox(self.box_velocity)
        self.QMIN.setObjectName(_fromUtf8("QMIN"))
        self.verticalLayout_2.addWidget(self.QMIN)
        self.QMAJ = QtGui.QCheckBox(self.box_velocity)
        self.QMAJ.setObjectName(_fromUtf8("QMAJ"))
        self.verticalLayout_2.addWidget(self.QMAJ)
        self.VMIN = QtGui.QCheckBox(self.box_velocity)
        self.VMIN.setObjectName(_fromUtf8("VMIN"))
        self.verticalLayout_2.addWidget(self.VMIN)
        self.VMAJ = QtGui.QCheckBox(self.box_velocity)
        self.VMAJ.setObjectName(_fromUtf8("VMAJ"))
        self.verticalLayout_2.addWidget(self.VMAJ)
        self.Q2G = QtGui.QCheckBox(self.box_velocity)
        self.Q2G.setObjectName(_fromUtf8("Q2G"))
        self.verticalLayout_2.addWidget(self.Q2G)
        self.Q2D = QtGui.QCheckBox(self.box_velocity)
        self.Q2D.setObjectName(_fromUtf8("Q2D"))
        self.verticalLayout_2.addWidget(self.Q2D)
        self.VZMX = QtGui.QCheckBox(self.box_velocity)
        self.VZMX.setObjectName(_fromUtf8("VZMX"))
        self.verticalLayout_2.addWidget(self.VZMX)
        self.VINF = QtGui.QCheckBox(self.box_velocity)
        self.VINF.setObjectName(_fromUtf8("VINF"))
        self.verticalLayout_2.addWidget(self.VINF)
        self.VSUP = QtGui.QCheckBox(self.box_velocity)
        self.VSUP.setObjectName(_fromUtf8("VSUP"))
        self.verticalLayout_2.addWidget(self.VSUP)
        self.QMAX = QtGui.QCheckBox(self.box_velocity)
        self.QMAX.setObjectName(_fromUtf8("QMAX"))
        self.verticalLayout_2.addWidget(self.QMAX)
        spacerItem21 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem21)
        self.gridLayout_16.addLayout(self.verticalLayout_2, 1, 0, 1, 1)
        self.gridLayout_13.addWidget(self.box_velocity, 0, 1, 1, 1)
        self.box_stress = QtGui.QGroupBox(self.tabOut)
        self.box_stress.setCheckable(True)
        self.box_stress.setChecked(True)
        self.box_stress.setObjectName(_fromUtf8("box_stress"))
        self.gridLayout_20 = QtGui.QGridLayout(self.box_stress)
        self.gridLayout_20.setObjectName(_fromUtf8("gridLayout_20"))
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.TAUF = QtGui.QCheckBox(self.box_stress)
        self.TAUF.setObjectName(_fromUtf8("TAUF"))
        self.verticalLayout_5.addWidget(self.TAUF)
        self.CHAR = QtGui.QCheckBox(self.box_stress)
        self.CHAR.setObjectName(_fromUtf8("CHAR"))
        self.verticalLayout_5.addWidget(self.CHAR)
        self.EMAX = QtGui.QCheckBox(self.box_stress)
        self.EMAX.setObjectName(_fromUtf8("EMAX"))
        self.verticalLayout_5.addWidget(self.EMAX)
        spacerItem22 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem22)
        self.gridLayout_20.addLayout(self.verticalLayout_5, 0, 0, 1, 1)
        self.gridLayout_13.addWidget(self.box_stress, 1, 1, 1, 1)
        self.box_coef = QtGui.QGroupBox(self.tabOut)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.box_coef.sizePolicy().hasHeightForWidth())
        self.box_coef.setSizePolicy(sizePolicy)
        self.box_coef.setCheckable(True)
        self.box_coef.setChecked(True)
        self.box_coef.setObjectName(_fromUtf8("box_coef"))
        self.gridLayout_19 = QtGui.QGridLayout(self.box_coef)
        self.gridLayout_19.setObjectName(_fromUtf8("gridLayout_19"))
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.KMIN = QtGui.QCheckBox(self.box_coef)
        self.KMIN.setObjectName(_fromUtf8("KMIN"))
        self.verticalLayout_6.addWidget(self.KMIN)
        self.KMAJ = QtGui.QCheckBox(self.box_coef)
        self.KMAJ.setObjectName(_fromUtf8("KMAJ"))
        self.verticalLayout_6.addWidget(self.KMAJ)
        self.FR = QtGui.QCheckBox(self.box_coef)
        self.FR.setObjectName(_fromUtf8("FR"))
        self.verticalLayout_6.addWidget(self.FR)
        self.BETA = QtGui.QCheckBox(self.box_coef)
        self.BETA.setObjectName(_fromUtf8("BETA"))
        self.verticalLayout_6.addWidget(self.BETA)
        spacerItem23 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem23)
        self.gridLayout_19.addLayout(self.verticalLayout_6, 0, 0, 1, 1)
        self.gridLayout_13.addWidget(self.box_coef, 1, 2, 1, 1)
        self.gridLayout_14.addLayout(self.gridLayout_13, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabOut, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.buttonBox_valid = QtGui.QDialogButtonBox(Parameters)
        self.buttonBox_valid.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox_valid.setObjectName(_fromUtf8("buttonBox_valid"))
        self.gridLayout.addWidget(self.buttonBox_valid, 1, 0, 1, 1)
        self.actionB_delete_law = QtGui.QAction(Parameters)
        self.actionB_delete_law.setObjectName(_fromUtf8("actionB_delete_law"))
        self.actionB_load_law = QtGui.QAction(Parameters)
        self.actionB_load_law.setObjectName(_fromUtf8("actionB_load_law"))
        self.actionRadioButton_law = QtGui.QAction(Parameters)
        self.actionRadioButton_law.setObjectName(_fromUtf8("actionRadioButton_law"))
        self.actionEvenement = QtGui.QAction(Parameters)
        self.actionEvenement.setObjectName(_fromUtf8("actionEvenement"))
        self.actionbox_WaterLevel = QtGui.QAction(Parameters)
        self.actionbox_WaterLevel.setObjectName(_fromUtf8("actionbox_WaterLevel"))
        self.actionbox_velocity = QtGui.QAction(Parameters)
        self.actionbox_velocity.setObjectName(_fromUtf8("actionbox_velocity"))
        self.actionbox_hydro = QtGui.QAction(Parameters)
        self.actionbox_hydro.setObjectName(_fromUtf8("actionbox_hydro"))
        self.actionbox_time = QtGui.QAction(Parameters)
        self.actionbox_time.setObjectName(_fromUtf8("actionbox_time"))
        self.actionbox_stress = QtGui.QAction(Parameters)
        self.actionbox_stress.setObjectName(_fromUtf8("actionbox_stress"))
        self.actionbox_coef = QtGui.QAction(Parameters)
        self.actionbox_coef.setObjectName(_fromUtf8("actionbox_coef"))

        self.retranslateUi(Parameters)
        self.tabWidget.setCurrentIndex(0)
        self.option.setCurrentIndex(0)
        QtCore.QObject.connect(self.b_load_law, QtCore.SIGNAL(_fromUtf8("clicked()")), self.actionB_load_law.trigger)
        QtCore.QObject.connect(self.b_delete_law, QtCore.SIGNAL(_fromUtf8("clicked()")), self.actionB_delete_law.trigger)
        QtCore.QObject.connect(self.evenement, QtCore.SIGNAL(_fromUtf8("clicked()")), self.actionEvenement.trigger)
        QtCore.QObject.connect(self.radioButton_law, QtCore.SIGNAL(_fromUtf8("clicked()")), self.actionRadioButton_law.trigger)
        QtCore.QObject.connect(self.box_coef, QtCore.SIGNAL(_fromUtf8("clicked()")), self.actionbox_coef.trigger)
        QtCore.QObject.connect(self.box_hydro, QtCore.SIGNAL(_fromUtf8("clicked()")), self.actionbox_hydro.trigger)
        QtCore.QObject.connect(self.box_stress, QtCore.SIGNAL(_fromUtf8("clicked()")), self.actionbox_stress.trigger)
        QtCore.QObject.connect(self.box_velocity, QtCore.SIGNAL(_fromUtf8("clicked()")), self.actionbox_velocity.trigger)
        QtCore.QObject.connect(self.box_time, QtCore.SIGNAL(_fromUtf8("clicked()")), self.actionbox_time.trigger)
        QtCore.QObject.connect(self.box_WaterLevel, QtCore.SIGNAL(_fromUtf8("clicked()")), self.actionbox_WaterLevel.trigger)
        QtCore.QMetaObject.connectSlotsByName(Parameters)

    def retranslateUi(self, Parameters):
        Parameters.setWindowTitle(_translate("Parameters", "Mascaret Options", None))
        self.b_delete_law.setText(_translate("Parameters", "Delete", None))
        self.b_load_law.setText(_translate("Parameters", "Load", None))
        self.label.setText(_translate("Parameters", "The hydraulic observation of event :", None))
        self.evenement.setText(_translate("Parameters", "Event", None))
        self.radioButton_law.setText(_translate("Parameters", "Creation of  law files", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabConfig), _translate("Parameters", "Configuration", None))
        self.perteChargeConf.setText(_translate("Parameters", "Automatic head losses at junctions", None))
        self.interpolLinStrickler.setText(_translate("Parameters", "Linear interpolation of friction coefficients ", None))
        self.label_elevCoteArrivFront.setText(_translate("Parameters", "Level threshold identifying the wave : ", None))
        self.label_compositionLits.setText(_translate("Parameters", "Cross section layout : ", None))
        self.compositionLits.setItemText(0, _translate("Parameters", "None", None))
        self.compositionLits.setItemText(1, _translate("Parameters", "Debord model", None))
        self.compositionLits.setItemText(2, _translate("Parameters", "Bottom/bank model", None))
        self.litMajeur.setText(_translate("Parameters", "Progressive overflow type  of major river bed", None))
        self.zoneStock.setText(_translate("Parameters", "Progressive overflow type  of storage area", None))
        self.conservFrotVertical.setText(_translate("Parameters", "Conservation of friction on vertical walls", None))
        self.elevCoteArrivFront.setSuffix(_translate("Parameters", " m", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabPhyMod), _translate("Parameters", "Physic model", None))
        self.optimisNoyauTrans.setText(_translate("Parameters", "Optimization of the super-critical kernel", None))
        self.perteChargeAutoElargissement.setText(_translate("Parameters", "Automatic head loss in case of enlargement", None))
        self.implicitNoyauTrans.setText(_translate("Parameters", "Implicitation of the super-critical kernel", None))
        self.calcOndeSubmersion.setText(_translate("Parameters", "Computation of a dam break flood wave", None))
        self.termesNonHydrostatiques.setText(_translate("Parameters", "Non-hydrostsatic term for super-critical kernel", None))
        self.attenuationConvection.setText(_translate("Parameters", "Reduced momentum equation", None))
        self.pasTempsVar.setText(_translate("Parameters", "Variable time step depending on the Courant number", None))
        self.label_froudeLimCondLim.setText(_translate("Parameters", "Limit Froude number for boundary conditions : ", None))
        self.traitImplicitFrot.setText(_translate("Parameters", "Implicitation of friction", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabNum), _translate("Parameters", "Numerical", None))
        self.label_tempsInit.setText(_translate("Parameters", "Initial time : ", None))
        self.tempsInit.setSuffix(_translate("Parameters", " s", None))
        self.label_tempsMax.setText(_translate("Parameters", "Max time : ", None))
        self.label_coteMax.setText(_translate("Parameters", "Max control water level : ", None))
        self.critereArret.setItemText(0, _translate("Parameters", "Max time", None))
        self.critereArret.setItemText(1, _translate("Parameters", "Max number of time steps", None))
        self.critereArret.setItemText(2, _translate("Parameters", "Max control water level", None))
        self.label_abscisseControle.setText(_translate("Parameters", "Control point abscissa : ", None))
        self.label_nbPasTemps.setText(_translate("Parameters", "Max number of time steps : ", None))
        self.label_nbCourant.setText(_translate("Parameters", "Courant number : ", None))
        self.label_pasTemps.setText(_translate("Parameters", "Time step : ", None))
        self.label_critereArret.setText(_translate("Parameters", "Criteria for stopping calculations : ", None))
        self.pasTemps.setSuffix(_translate("Parameters", " s", None))
        self.coteMax.setSuffix(_translate("Parameters", " m", None))
        self.tempsMax.setSuffix(_translate("Parameters", " s", None))
        self.label_biefControle.setText(_translate("Parameters", "Control point  reach : ", None))
        self.abscisseControle.setSuffix(_translate("Parameters", " m", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabTemp), _translate("Parameters", "Temporal", None))
        self.initialisationAuto.setText(_translate("Parameters", "Initialisation with a steady run", None))
        self.LigEauInit.setText(_translate("Parameters", "Presence of an initial water level", None))
        self.repriseCalcul.setText(_translate("Parameters", "Restart the computation", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabInitBound), _translate("Parameters", "Initial boundaries", None))
        self.label_pasStock.setText(_translate("Parameters", "Number of the first time step", None))
        self.impressionligneEauInitiale.setText(_translate("Parameters", "Initial water level", None))
        self.impressionCalcul.setText(_translate("Parameters", "Write the listing along with computation progress", None))
        self.impressionPlanimetrage.setText(_translate("Parameters", "Vertical discretization of the Cross section", None))
        self.impressionReseau.setText(_translate("Parameters", "Network", None))
        self.label_pasImpression.setText(_translate("Parameters", "Write data all N time steps", None))
        self.impressionGeometrie.setText(_translate("Parameters", "Geometry", None))
        self.label_ecartInterBranch.setText(_translate("Parameters", "Distance between reaches (m)", None))
        self.label_premPasTpsStock.setText(_translate("Parameters", "Number of the first time step", None))
        self.impressionLoiHydraulique.setText(_translate("Parameters", "Hydraulic laws used", None))
        self.label_option.setText(_translate("Parameters", "Recorded Variables", None))
        self.option.setItemText(0, _translate("Parameters", "At all computational profiles", None))
        self.option.setItemText(1, _translate("Parameters", "Output points layer", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabRes), _translate("Parameters", "Results", None))
        self.box_hydro.setTitle(_translate("Parameters", "Hydraulic variables", None))
        self.S1.setText(_translate("Parameters", "Wetted area of minor river bed", None))
        self.S2.setText(_translate("Parameters", "Wetted area of major river bed", None))
        self.B1.setText(_translate("Parameters", "Surface width of minor river bed", None))
        self.B2.setText(_translate("Parameters", "Surface width of major river bed", None))
        self.BS.setText(_translate("Parameters", "Surface width of storage area", None))
        self.P1.setText(_translate("Parameters", "Wetted perimeter of minor river bed", None))
        self.P2.setText(_translate("Parameters", "Wetted perimeter of major river bed", None))
        self.RH1.setText(_translate("Parameters", "Hydaulic radius of minor river bed", None))
        self.RH2.setText(_translate("Parameters", "Hydaulic radius of major river bed", None))
        self.SS.setText(_translate("Parameters", "Wetted area of storage area", None))
        self.VOL.setText(_translate("Parameters", "Cumulative volume of the active river bed", None))
        self.VOLS.setText(_translate("Parameters", "Cumulative volume of the storage area", None))
        self.BMAX.setText(_translate("Parameters", "Maximum surface width", None))
        self.box_WaterLevel.setTitle(_translate("Parameters", "Water levels and flow depths", None))
        self.ZREF.setText(_translate("Parameters", "Bottom elevation", None))
        self.RGC.setText(_translate("Parameters", "Left bank water level", None))
        self.RDC.setText(_translate("Parameters", "Right bank water level", None))
        self.Z.setText(_translate("Parameters", "Water level", None))
        self.Y.setText(_translate("Parameters", "Water depth", None))
        self.HMOY.setText(_translate("Parameters", "Average water depth", None))
        self.ZMAX.setText(_translate("Parameters", "Maximal water level", None))
        self.ZMIN.setText(_translate("Parameters", "Minimal water level", None))
        self.box_time.setTitle(_translate("Parameters", "Time", None))
        self.TZMA.setText(_translate("Parameters", "Date of maximal water level", None))
        self.TZMI.setText(_translate("Parameters", "Date of minimal water level", None))
        self.TOND.setText(_translate("Parameters", "Arrival time of the floodwave", None))
        self.TQMA.setText(_translate("Parameters", "Date of maximum flow rate", None))
        self.box_velocity.setTitle(_translate("Parameters", "Flow rates and velocities", None))
        self.QMIN.setText(_translate("Parameters", "Flow rate in minor river bed", None))
        self.QMAJ.setText(_translate("Parameters", "Flow rate in major river bed", None))
        self.VMIN.setText(_translate("Parameters", "Velocity of minor river bed", None))
        self.VMAJ.setText(_translate("Parameters", "Velocity of major river bed", None))
        self.Q2G.setText(_translate("Parameters", "Flow rate in left major river bed", None))
        self.Q2D.setText(_translate("Parameters", "Flow rate in right major river bed", None))
        self.VZMX.setText(_translate("Parameters", "Velocity for the maximal water level", None))
        self.VINF.setText(_translate("Parameters", "Minimum minor river bed velocity", None))
        self.VSUP.setText(_translate("Parameters", "Maximum major river bed velocity", None))
        self.QMAX.setText(_translate("Parameters", "Maximum flow rate", None))
        self.box_stress.setTitle(_translate("Parameters", "Shear stresses and energy", None))
        self.TAUF.setText(_translate("Parameters", "Bottom shear stress", None))
        self.CHAR.setText(_translate("Parameters", "Hydraulic head", None))
        self.EMAX.setText(_translate("Parameters", "Maximum energy", None))
        self.box_coef.setTitle(_translate("Parameters", "Non-dimensional numbers and coef.", None))
        self.KMIN.setText(_translate("Parameters", "Minor friction coefficient", None))
        self.KMAJ.setText(_translate("Parameters", "Major friction coefficient", None))
        self.FR.setText(_translate("Parameters", "Froude number", None))
        self.BETA.setText(_translate("Parameters", "Coefficient beta of Debord\'s formula", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabOut), _translate("Parameters", "Outputs", None))
        self.actionB_delete_law.setText(_translate("Parameters", "b_delete_law", None))
        self.actionB_load_law.setText(_translate("Parameters", "b_load_law", None))
        self.actionRadioButton_law.setText(_translate("Parameters", "radioButton_law", None))
        self.actionEvenement.setText(_translate("Parameters", "evenement", None))
        self.actionEvenement.setToolTip(_translate("Parameters", "evenement", None))
        self.actionbox_WaterLevel.setText(_translate("Parameters", "box_WaterLevel", None))
        self.actionbox_velocity.setText(_translate("Parameters", "box_velocity", None))
        self.actionbox_hydro.setText(_translate("Parameters", "box_hydro", None))
        self.actionbox_time.setText(_translate("Parameters", "box_time", None))
        self.actionbox_stress.setText(_translate("Parameters", "box_stress", None))
        self.actionbox_coef.setText(_translate("Parameters", "box_coef", None))

